/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Apply FIO Factor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.ApplyFIOFactor#getValueReference <em>Value Reference</em>}</li>
 *   <li>{@link it.unibo.fPML.ApplyFIOFactor#getValuePrimitive <em>Value Primitive</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getApplyFIOFactor()
 * @model
 * @generated
 */
public interface ApplyFIOFactor extends EObject
{
  /**
   * Returns the value of the '<em><b>Value Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Reference</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Reference</em>' reference.
   * @see #setValueReference(EffectFullReference)
   * @see it.unibo.fPML.FPMLPackage#getApplyFIOFactor_ValueReference()
   * @model
   * @generated
   */
  EffectFullReference getValueReference();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ApplyFIOFactor#getValueReference <em>Value Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Reference</em>' reference.
   * @see #getValueReference()
   * @generated
   */
  void setValueReference(EffectFullReference value);

  /**
   * Returns the value of the '<em><b>Value Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Primitive</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Primitive</em>' containment reference.
   * @see #setValuePrimitive(PrimitiveEffectFullValue)
   * @see it.unibo.fPML.FPMLPackage#getApplyFIOFactor_ValuePrimitive()
   * @model containment="true"
   * @generated
   */
  PrimitiveEffectFullValue getValuePrimitive();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ApplyFIOFactor#getValuePrimitive <em>Value Primitive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Primitive</em>' containment reference.
   * @see #getValuePrimitive()
   * @generated
   */
  void setValuePrimitive(PrimitiveEffectFullValue value);

} // ApplyFIOFactor
