/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Apply FIO</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.ApplyFIO#getFunctionType <em>Function Type</em>}</li>
 *   <li>{@link it.unibo.fPML.ApplyFIO#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getApplyFIO()
 * @model
 * @generated
 */
public interface ApplyFIO extends PrimitiveEffectFullFunction
{
  /**
   * Returns the value of the '<em><b>Function Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Type</em>' containment reference.
   * @see #setFunctionType(EffectFullFunctionType)
   * @see it.unibo.fPML.FPMLPackage#getApplyFIO_FunctionType()
   * @model containment="true"
   * @generated
   */
  EffectFullFunctionType getFunctionType();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ApplyFIO#getFunctionType <em>Function Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Type</em>' containment reference.
   * @see #getFunctionType()
   * @generated
   */
  void setFunctionType(EffectFullFunctionType value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(EffectFullReference)
   * @see it.unibo.fPML.FPMLPackage#getApplyFIO_Value()
   * @model
   * @generated
   */
  EffectFullReference getValue();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ApplyFIO#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EffectFullReference value);

} // ApplyFIO
