/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Apply FFactor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.ApplyFFactor#getValueReference <em>Value Reference</em>}</li>
 *   <li>{@link it.unibo.fPML.ApplyFFactor#getValueExpression <em>Value Expression</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getApplyFFactor()
 * @model
 * @generated
 */
public interface ApplyFFactor extends EObject
{
  /**
   * Returns the value of the '<em><b>Value Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Reference</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Reference</em>' reference.
   * @see #setValueReference(PureFunction)
   * @see it.unibo.fPML.FPMLPackage#getApplyFFactor_ValueReference()
   * @model
   * @generated
   */
  PureFunction getValueReference();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ApplyFFactor#getValueReference <em>Value Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Reference</em>' reference.
   * @see #getValueReference()
   * @generated
   */
  void setValueReference(PureFunction value);

  /**
   * Returns the value of the '<em><b>Value Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Expression</em>' containment reference.
   * @see #setValueExpression(Expression)
   * @see it.unibo.fPML.FPMLPackage#getApplyFFactor_ValueExpression()
   * @model containment="true"
   * @generated
   */
  Expression getValueExpression();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ApplyFFactor#getValueExpression <em>Value Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Expression</em>' containment reference.
   * @see #getValueExpression()
   * @generated
   */
  void setValueExpression(Expression value);

} // ApplyFFactor
