/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect Full Prod Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.EffectFullProdValue#getProdAdtElement1 <em>Prod Adt Element1</em>}</li>
 *   <li>{@link it.unibo.fPML.EffectFullProdValue#getProdAdtElement2 <em>Prod Adt Element2</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getEffectFullProdValue()
 * @model
 * @generated
 */
public interface EffectFullProdValue extends EffectFullAdtValue
{
  /**
   * Returns the value of the '<em><b>Prod Adt Element1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prod Adt Element1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prod Adt Element1</em>' containment reference.
   * @see #setProdAdtElement1(EffectFullAdtValue)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullProdValue_ProdAdtElement1()
   * @model containment="true"
   * @generated
   */
  EffectFullAdtValue getProdAdtElement1();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullProdValue#getProdAdtElement1 <em>Prod Adt Element1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prod Adt Element1</em>' containment reference.
   * @see #getProdAdtElement1()
   * @generated
   */
  void setProdAdtElement1(EffectFullAdtValue value);

  /**
   * Returns the value of the '<em><b>Prod Adt Element2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prod Adt Element2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prod Adt Element2</em>' containment reference.
   * @see #setProdAdtElement2(EffectFullAdtValue)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullProdValue_ProdAdtElement2()
   * @model containment="true"
   * @generated
   */
  EffectFullAdtValue getProdAdtElement2();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullProdValue#getProdAdtElement2 <em>Prod Adt Element2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prod Adt Element2</em>' containment reference.
   * @see #getProdAdtElement2()
   * @generated
   */
  void setProdAdtElement2(EffectFullAdtValue value);

} // EffectFullProdValue
