/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect Full If Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.EffectFullIfBody#getFunctionReference <em>Function Reference</em>}</li>
 *   <li>{@link it.unibo.fPML.EffectFullIfBody#getFunctionExpression <em>Function Expression</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getEffectFullIfBody()
 * @model
 * @generated
 */
public interface EffectFullIfBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Function Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Reference</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Reference</em>' reference.
   * @see #setFunctionReference(EffectFullFunction)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullIfBody_FunctionReference()
   * @model
   * @generated
   */
  EffectFullFunction getFunctionReference();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullIfBody#getFunctionReference <em>Function Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Reference</em>' reference.
   * @see #getFunctionReference()
   * @generated
   */
  void setFunctionReference(EffectFullFunction value);

  /**
   * Returns the value of the '<em><b>Function Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Expression</em>' containment reference.
   * @see #setFunctionExpression(EffectFullExpression)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullIfBody_FunctionExpression()
   * @model containment="true"
   * @generated
   */
  EffectFullExpression getFunctionExpression();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullIfBody#getFunctionExpression <em>Function Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Expression</em>' containment reference.
   * @see #getFunctionExpression()
   * @generated
   */
  void setFunctionExpression(EffectFullExpression value);

} // EffectFullIfBody
