/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect Full Algebraic Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.EffectFullAlgebraicType#getEffectFullAdtElement1 <em>Effect Full Adt Element1</em>}</li>
 *   <li>{@link it.unibo.fPML.EffectFullAlgebraicType#getEffectFullAdtElement2 <em>Effect Full Adt Element2</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getEffectFullAlgebraicType()
 * @model
 * @generated
 */
public interface EffectFullAlgebraicType extends EffectFullType
{
  /**
   * Returns the value of the '<em><b>Effect Full Adt Element1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Effect Full Adt Element1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effect Full Adt Element1</em>' containment reference.
   * @see #setEffectFullAdtElement1(Type)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullAlgebraicType_EffectFullAdtElement1()
   * @model containment="true"
   * @generated
   */
  Type getEffectFullAdtElement1();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullAlgebraicType#getEffectFullAdtElement1 <em>Effect Full Adt Element1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effect Full Adt Element1</em>' containment reference.
   * @see #getEffectFullAdtElement1()
   * @generated
   */
  void setEffectFullAdtElement1(Type value);

  /**
   * Returns the value of the '<em><b>Effect Full Adt Element2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Effect Full Adt Element2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effect Full Adt Element2</em>' containment reference.
   * @see #setEffectFullAdtElement2(EObject)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullAlgebraicType_EffectFullAdtElement2()
   * @model containment="true"
   * @generated
   */
  EObject getEffectFullAdtElement2();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullAlgebraicType#getEffectFullAdtElement2 <em>Effect Full Adt Element2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effect Full Adt Element2</em>' containment reference.
   * @see #getEffectFullAdtElement2()
   * @generated
   */
  void setEffectFullAdtElement2(EObject value);

} // EffectFullAlgebraicType
