/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect Full Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getEffectFullPrimitive()
 * @model
 * @generated
 */
public interface EffectFullPrimitive extends PrimitiveFunction, EffectFullBodyContent
{
} // EffectFullPrimitive
