/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect Full Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.EffectFullFunction#getReturnType <em>Return Type</em>}</li>
 *   <li>{@link it.unibo.fPML.EffectFullFunction#getArg <em>Arg</em>}</li>
 *   <li>{@link it.unibo.fPML.EffectFullFunction#getFunctionBody <em>Function Body</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getEffectFullFunction()
 * @model
 * @generated
 */
public interface EffectFullFunction extends Function
{
  /**
   * Returns the value of the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' containment reference.
   * @see #setReturnType(IOType)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullFunction_ReturnType()
   * @model containment="true"
   * @generated
   */
  IOType getReturnType();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullFunction#getReturnType <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' containment reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(IOType value);

  /**
   * Returns the value of the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' containment reference.
   * @see #setArg(EffectFullArgument)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullFunction_Arg()
   * @model containment="true"
   * @generated
   */
  EffectFullArgument getArg();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullFunction#getArg <em>Arg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' containment reference.
   * @see #getArg()
   * @generated
   */
  void setArg(EffectFullArgument value);

  /**
   * Returns the value of the '<em><b>Function Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Body</em>' containment reference.
   * @see #setFunctionBody(FunctionBodyEffectFull)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullFunction_FunctionBody()
   * @model containment="true"
   * @generated
   */
  FunctionBodyEffectFull getFunctionBody();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullFunction#getFunctionBody <em>Function Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Body</em>' containment reference.
   * @see #getFunctionBody()
   * @generated
   */
  void setFunctionBody(FunctionBodyEffectFull value);

} // EffectFullFunction
