/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect Full Sum Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.EffectFullSumValue#getSumAdtElement1 <em>Sum Adt Element1</em>}</li>
 *   <li>{@link it.unibo.fPML.EffectFullSumValue#getSumAdtElement2 <em>Sum Adt Element2</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getEffectFullSumValue()
 * @model
 * @generated
 */
public interface EffectFullSumValue extends EffectFullAlgebraicType
{
  /**
   * Returns the value of the '<em><b>Sum Adt Element1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sum Adt Element1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sum Adt Element1</em>' containment reference.
   * @see #setSumAdtElement1(EffectFullExpression)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullSumValue_SumAdtElement1()
   * @model containment="true"
   * @generated
   */
  EffectFullExpression getSumAdtElement1();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullSumValue#getSumAdtElement1 <em>Sum Adt Element1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sum Adt Element1</em>' containment reference.
   * @see #getSumAdtElement1()
   * @generated
   */
  void setSumAdtElement1(EffectFullExpression value);

  /**
   * Returns the value of the '<em><b>Sum Adt Element2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sum Adt Element2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sum Adt Element2</em>' containment reference.
   * @see #setSumAdtElement2(EffectFullExpression)
   * @see it.unibo.fPML.FPMLPackage#getEffectFullSumValue_SumAdtElement2()
   * @model containment="true"
   * @generated
   */
  EffectFullExpression getSumAdtElement2();

  /**
   * Sets the value of the '{@link it.unibo.fPML.EffectFullSumValue#getSumAdtElement2 <em>Sum Adt Element2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sum Adt Element2</em>' containment reference.
   * @see #getSumAdtElement2()
   * @generated
   */
  void setSumAdtElement2(EffectFullExpression value);

} // EffectFullSumValue
