/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extract Effect Full</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.ExtractEffectFull#getData <em>Data</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getExtractEffectFull()
 * @model
 * @generated
 */
public interface ExtractEffectFull extends PrimitiveEffectFullFunction
{
  /**
   * Returns the value of the '<em><b>Data</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' reference.
   * @see #setData(EffectFullData)
   * @see it.unibo.fPML.FPMLPackage#getExtractEffectFull_Data()
   * @model
   * @generated
   */
  EffectFullData getData();

  /**
   * Sets the value of the '{@link it.unibo.fPML.ExtractEffectFull#getData <em>Data</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' reference.
   * @see #getData()
   * @generated
   */
  void setData(EffectFullData value);

} // ExtractEffectFull
