/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see it.unibo.fPML.FPMLPackage
 * @generated
 */
public interface FPMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FPMLFactory eINSTANCE = it.unibo.fPML.impl.FPMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Pure Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Block</em>'.
   * @generated
   */
  PureBlock createPureBlock();

  /**
   * Returns a new object of class '<em>Pure Function Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Function Block</em>'.
   * @generated
   */
  PureFunctionBlock createPureFunctionBlock();

  /**
   * Returns a new object of class '<em>Data Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Block</em>'.
   * @generated
   */
  DataBlock createDataBlock();

  /**
   * Returns a new object of class '<em>Effect Full Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Block</em>'.
   * @generated
   */
  EffectFullBlock createEffectFullBlock();

  /**
   * Returns a new object of class '<em>Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data</em>'.
   * @generated
   */
  Data createData();

  /**
   * Returns a new object of class '<em>Adt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Adt</em>'.
   * @generated
   */
  Adt createAdt();

  /**
   * Returns a new object of class '<em>Sum Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sum Type</em>'.
   * @generated
   */
  SumType createSumType();

  /**
   * Returns a new object of class '<em>Prod Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Prod Type</em>'.
   * @generated
   */
  ProdType createProdType();

  /**
   * Returns a new object of class '<em>Pure Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Function</em>'.
   * @generated
   */
  PureFunction createPureFunction();

  /**
   * Returns a new object of class '<em>Effect Full Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Function</em>'.
   * @generated
   */
  EffectFullFunction createEffectFullFunction();

  /**
   * Returns a new object of class '<em>Main Func</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Func</em>'.
   * @generated
   */
  MainFunc createMainFunc();

  /**
   * Returns a new object of class '<em>Chain Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chain Element</em>'.
   * @generated
   */
  ChainElement createChainElement();

  /**
   * Returns a new object of class '<em>Initial Pure Chain Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Pure Chain Element</em>'.
   * @generated
   */
  InitialPureChainElement createInitialPureChainElement();

  /**
   * Returns a new object of class '<em>Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function</em>'.
   * @generated
   */
  Function createFunction();

  /**
   * Returns a new object of class '<em>Effect Full Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Argument</em>'.
   * @generated
   */
  EffectFullArgument createEffectFullArgument();

  /**
   * Returns a new object of class '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument</em>'.
   * @generated
   */
  Argument createArgument();

  /**
   * Returns a new object of class '<em>Function Body Pure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Body Pure</em>'.
   * @generated
   */
  FunctionBodyPure createFunctionBodyPure();

  /**
   * Returns a new object of class '<em>Function Body Effect Full</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Body Effect Full</em>'.
   * @generated
   */
  FunctionBodyEffectFull createFunctionBodyEffectFull();

  /**
   * Returns a new object of class '<em>Empty Function Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Empty Function Body</em>'.
   * @generated
   */
  EmptyFunctionBody createEmptyFunctionBody();

  /**
   * Returns a new object of class '<em>Composition Function Body Pure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition Function Body Pure</em>'.
   * @generated
   */
  CompositionFunctionBodyPure createCompositionFunctionBodyPure();

  /**
   * Returns a new object of class '<em>Composition Function Body Effect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition Function Body Effect</em>'.
   * @generated
   */
  CompositionFunctionBodyEffect createCompositionFunctionBodyEffect();

  /**
   * Returns a new object of class '<em>IO Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IO Type</em>'.
   * @generated
   */
  IOType createIOType();

  /**
   * Returns a new object of class '<em>Value Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value Type</em>'.
   * @generated
   */
  ValueType createValueType();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Integer Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integer Type</em>'.
   * @generated
   */
  IntegerType createIntegerType();

  /**
   * Returns a new object of class '<em>String Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Type</em>'.
   * @generated
   */
  StringType createStringType();

  /**
   * Returns a new object of class '<em>Unit Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unit Type</em>'.
   * @generated
   */
  UnitType createUnitType();

  /**
   * Returns a new object of class '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Type</em>'.
   * @generated
   */
  DataType createDataType();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FPMLPackage getFPMLPackage();

} //FPMLFactory
