/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see it.unibo.fPML.FPMLPackage
 * @generated
 */
public interface FPMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FPMLFactory eINSTANCE = it.unibo.fPML.impl.FPMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Pure Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Block</em>'.
   * @generated
   */
  PureBlock createPureBlock();

  /**
   * Returns a new object of class '<em>Pure Function Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Function Block</em>'.
   * @generated
   */
  PureFunctionBlock createPureFunctionBlock();

  /**
   * Returns a new object of class '<em>Pure Data Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Data Block</em>'.
   * @generated
   */
  PureDataBlock createPureDataBlock();

  /**
   * Returns a new object of class '<em>Pure Value Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Value Block</em>'.
   * @generated
   */
  PureValueBlock createPureValueBlock();

  /**
   * Returns a new object of class '<em>Effect Full Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Block</em>'.
   * @generated
   */
  EffectFullBlock createEffectFullBlock();

  /**
   * Returns a new object of class '<em>Effect Full Data Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Data Block</em>'.
   * @generated
   */
  EffectFullDataBlock createEffectFullDataBlock();

  /**
   * Returns a new object of class '<em>Effect Full Value Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Value Block</em>'.
   * @generated
   */
  EffectFullValueBlock createEffectFullValueBlock();

  /**
   * Returns a new object of class '<em>Effect Full Function Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Function Block</em>'.
   * @generated
   */
  EffectFullFunctionBlock createEffectFullFunctionBlock();

  /**
   * Returns a new object of class '<em>Pure Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Data</em>'.
   * @generated
   */
  PureData createPureData();

  /**
   * Returns a new object of class '<em>Pure Function Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Function Definition</em>'.
   * @generated
   */
  PureFunctionDefinition createPureFunctionDefinition();

  /**
   * Returns a new object of class '<em>Effect Full Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Data</em>'.
   * @generated
   */
  EffectFullData createEffectFullData();

  /**
   * Returns a new object of class '<em>Effect Full Function Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Function Definition</em>'.
   * @generated
   */
  EffectFullFunctionDefinition createEffectFullFunctionDefinition();

  /**
   * Returns a new object of class '<em>Main Func</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Func</em>'.
   * @generated
   */
  MainFunc createMainFunc();

  /**
   * Returns a new object of class '<em>Additional Pure Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Additional Pure Argument</em>'.
   * @generated
   */
  AdditionalPureArgument createAdditionalPureArgument();

  /**
   * Returns a new object of class '<em>Additional Effect Full Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Additional Effect Full Argument</em>'.
   * @generated
   */
  AdditionalEffectFullArgument createAdditionalEffectFullArgument();

  /**
   * Returns a new object of class '<em>Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function</em>'.
   * @generated
   */
  Function createFunction();

  /**
   * Returns a new object of class '<em>Pure Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Function</em>'.
   * @generated
   */
  PureFunction createPureFunction();

  /**
   * Returns a new object of class '<em>Effect Full Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Function</em>'.
   * @generated
   */
  EffectFullFunction createEffectFullFunction();

  /**
   * Returns a new object of class '<em>Primitive Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Function</em>'.
   * @generated
   */
  PrimitiveFunction createPrimitiveFunction();

  /**
   * Returns a new object of class '<em>Effect Full Primitive</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Primitive</em>'.
   * @generated
   */
  EffectFullPrimitive createEffectFullPrimitive();

  /**
   * Returns a new object of class '<em>Effect Full Body Content</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Body Content</em>'.
   * @generated
   */
  EffectFullBodyContent createEffectFullBodyContent();

  /**
   * Returns a new object of class '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument</em>'.
   * @generated
   */
  Argument createArgument();

  /**
   * Returns a new object of class '<em>Effect Full Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Argument</em>'.
   * @generated
   */
  EffectFullArgument createEffectFullArgument();

  /**
   * Returns a new object of class '<em>Pure Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Argument</em>'.
   * @generated
   */
  PureArgument createPureArgument();

  /**
   * Returns a new object of class '<em>Function Body Pure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Body Pure</em>'.
   * @generated
   */
  FunctionBodyPure createFunctionBodyPure();

  /**
   * Returns a new object of class '<em>Function Body Effect Full</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Body Effect Full</em>'.
   * @generated
   */
  FunctionBodyEffectFull createFunctionBodyEffectFull();

  /**
   * Returns a new object of class '<em>Empty Function Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Empty Function Body</em>'.
   * @generated
   */
  EmptyFunctionBody createEmptyFunctionBody();

  /**
   * Returns a new object of class '<em>Composition Function Body Pure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition Function Body Pure</em>'.
   * @generated
   */
  CompositionFunctionBodyPure createCompositionFunctionBodyPure();

  /**
   * Returns a new object of class '<em>Composition Function Body Pure Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition Function Body Pure Factor</em>'.
   * @generated
   */
  CompositionFunctionBodyPureFactor createCompositionFunctionBodyPureFactor();

  /**
   * Returns a new object of class '<em>Composition Function Body Effect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition Function Body Effect</em>'.
   * @generated
   */
  CompositionFunctionBodyEffect createCompositionFunctionBodyEffect();

  /**
   * Returns a new object of class '<em>Composition Function Body Effect Full Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition Function Body Effect Full Factor</em>'.
   * @generated
   */
  CompositionFunctionBodyEffectFullFactor createCompositionFunctionBodyEffectFullFactor();

  /**
   * Returns a new object of class '<em>IO Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IO Type</em>'.
   * @generated
   */
  IOType createIOType();

  /**
   * Returns a new object of class '<em>Value Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value Type</em>'.
   * @generated
   */
  ValueType createValueType();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Effect Full Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Type</em>'.
   * @generated
   */
  EffectFullType createEffectFullType();

  /**
   * Returns a new object of class '<em>Void Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Void Type</em>'.
   * @generated
   */
  VoidType createVoidType();

  /**
   * Returns a new object of class '<em>Integer Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integer Type</em>'.
   * @generated
   */
  IntegerType createIntegerType();

  /**
   * Returns a new object of class '<em>String Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Type</em>'.
   * @generated
   */
  StringType createStringType();

  /**
   * Returns a new object of class '<em>Boolean Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Type</em>'.
   * @generated
   */
  BooleanType createBooleanType();

  /**
   * Returns a new object of class '<em>Unit Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unit Type</em>'.
   * @generated
   */
  UnitType createUnitType();

  /**
   * Returns a new object of class '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Type</em>'.
   * @generated
   */
  DataType createDataType();

  /**
   * Returns a new object of class '<em>Effect Full Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Data Type</em>'.
   * @generated
   */
  EffectFullDataType createEffectFullDataType();

  /**
   * Returns a new object of class '<em>Pure Function Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Function Type</em>'.
   * @generated
   */
  PureFunctionType createPureFunctionType();

  /**
   * Returns a new object of class '<em>Effect Full Function Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Function Type</em>'.
   * @generated
   */
  EffectFullFunctionType createEffectFullFunctionType();

  /**
   * Returns a new object of class '<em>Pure Algebraic Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Algebraic Type</em>'.
   * @generated
   */
  PureAlgebraicType createPureAlgebraicType();

  /**
   * Returns a new object of class '<em>Pure Sum Type Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Sum Type Factor</em>'.
   * @generated
   */
  PureSumTypeFactor createPureSumTypeFactor();

  /**
   * Returns a new object of class '<em>Pure Prod Type Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Prod Type Factor</em>'.
   * @generated
   */
  PureProdTypeFactor createPureProdTypeFactor();

  /**
   * Returns a new object of class '<em>Effect Full Algebraic Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Algebraic Type</em>'.
   * @generated
   */
  EffectFullAlgebraicType createEffectFullAlgebraicType();

  /**
   * Returns a new object of class '<em>Effect Full Sum Type Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Sum Type Factor</em>'.
   * @generated
   */
  EffectFullSumTypeFactor createEffectFullSumTypeFactor();

  /**
   * Returns a new object of class '<em>Effect Full Prod Type Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Prod Type Factor</em>'.
   * @generated
   */
  EffectFullProdTypeFactor createEffectFullProdTypeFactor();

  /**
   * Returns a new object of class '<em>Effect Full Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Expression</em>'.
   * @generated
   */
  EffectFullExpression createEffectFullExpression();

  /**
   * Returns a new object of class '<em>Effect Full Value Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Value Ref</em>'.
   * @generated
   */
  EffectFullValueRef createEffectFullValueRef();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Pure Value Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Value Ref</em>'.
   * @generated
   */
  PureValueRef createPureValueRef();

  /**
   * Returns a new object of class '<em>Primitive Pure Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Pure Function</em>'.
   * @generated
   */
  PrimitivePureFunction createPrimitivePureFunction();

  /**
   * Returns a new object of class '<em>Int To String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int To String</em>'.
   * @generated
   */
  IntToString createIntToString();

  /**
   * Returns a new object of class '<em>Int Pow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Pow</em>'.
   * @generated
   */
  IntPow createIntPow();

  /**
   * Returns a new object of class '<em>Plus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plus</em>'.
   * @generated
   */
  Plus createPlus();

  /**
   * Returns a new object of class '<em>Minus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Minus</em>'.
   * @generated
   */
  Minus createMinus();

  /**
   * Returns a new object of class '<em>Times</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Times</em>'.
   * @generated
   */
  Times createTimes();

  /**
   * Returns a new object of class '<em>Mod</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mod</em>'.
   * @generated
   */
  Mod createMod();

  /**
   * Returns a new object of class '<em>Left Pair</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Left Pair</em>'.
   * @generated
   */
  LeftPair createLeftPair();

  /**
   * Returns a new object of class '<em>Right Pair</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Right Pair</em>'.
   * @generated
   */
  RightPair createRightPair();

  /**
   * Returns a new object of class '<em>Apply F</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Apply F</em>'.
   * @generated
   */
  ApplyF createApplyF();

  /**
   * Returns a new object of class '<em>Apply FFactor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Apply FFactor</em>'.
   * @generated
   */
  ApplyFFactor createApplyFFactor();

  /**
   * Returns a new object of class '<em>Equals</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equals</em>'.
   * @generated
   */
  Equals createEquals();

  /**
   * Returns a new object of class '<em>Minor Equals</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Minor Equals</em>'.
   * @generated
   */
  MinorEquals createMinorEquals();

  /**
   * Returns a new object of class '<em>Major Equals</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Major Equals</em>'.
   * @generated
   */
  MajorEquals createMajorEquals();

  /**
   * Returns a new object of class '<em>Minor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Minor</em>'.
   * @generated
   */
  Minor createMinor();

  /**
   * Returns a new object of class '<em>Major</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Major</em>'.
   * @generated
   */
  Major createMajor();

  /**
   * Returns a new object of class '<em>Logic And</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logic And</em>'.
   * @generated
   */
  LogicAnd createLogicAnd();

  /**
   * Returns a new object of class '<em>Logic Or</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logic Or</em>'.
   * @generated
   */
  LogicOr createLogicOr();

  /**
   * Returns a new object of class '<em>Extract Pure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extract Pure</em>'.
   * @generated
   */
  ExtractPure createExtractPure();

  /**
   * Returns a new object of class '<em>Primitive Effect Full Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Effect Full Function</em>'.
   * @generated
   */
  PrimitiveEffectFullFunction createPrimitiveEffectFullFunction();

  /**
   * Returns a new object of class '<em>Primitive Print</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Print</em>'.
   * @generated
   */
  PrimitivePrint createPrimitivePrint();

  /**
   * Returns a new object of class '<em>Left Pair IO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Left Pair IO</em>'.
   * @generated
   */
  LeftPairIO createLeftPairIO();

  /**
   * Returns a new object of class '<em>Right Pair IO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Right Pair IO</em>'.
   * @generated
   */
  RightPairIO createRightPairIO();

  /**
   * Returns a new object of class '<em>Primitive Effect Full Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Effect Full Value</em>'.
   * @generated
   */
  PrimitiveEffectFullValue createPrimitiveEffectFullValue();

  /**
   * Returns a new object of class '<em>Primitive Random</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Random</em>'.
   * @generated
   */
  PrimitiveRandom createPrimitiveRandom();

  /**
   * Returns a new object of class '<em>Primitive Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Return</em>'.
   * @generated
   */
  PrimitiveReturn createPrimitiveReturn();

  /**
   * Returns a new object of class '<em>Primitive Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Time</em>'.
   * @generated
   */
  PrimitiveTime createPrimitiveTime();

  /**
   * Returns a new object of class '<em>Apply FIO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Apply FIO</em>'.
   * @generated
   */
  ApplyFIO createApplyFIO();

  /**
   * Returns a new object of class '<em>Apply FIO Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Apply FIO Factor</em>'.
   * @generated
   */
  ApplyFIOFactor createApplyFIOFactor();

  /**
   * Returns a new object of class '<em>Extract Effect Full</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extract Effect Full</em>'.
   * @generated
   */
  ExtractEffectFull createExtractEffectFull();

  /**
   * Returns a new object of class '<em>Pure Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Value</em>'.
   * @generated
   */
  PureValue createPureValue();

  /**
   * Returns a new object of class '<em>Effect Full Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Value</em>'.
   * @generated
   */
  EffectFullValue createEffectFullValue();

  /**
   * Returns a new object of class '<em>Recursive Effect Full Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Recursive Effect Full Expression</em>'.
   * @generated
   */
  RecursiveEffectFullExpression createRecursiveEffectFullExpression();

  /**
   * Returns a new object of class '<em>IO Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IO Expression</em>'.
   * @generated
   */
  IOExpression createIOExpression();

  /**
   * Returns a new object of class '<em>IO Pure Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IO Pure Function</em>'.
   * @generated
   */
  IOPureFunction createIOPureFunction();

  /**
   * Returns a new object of class '<em>Effect Full Lambda</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Lambda</em>'.
   * @generated
   */
  EffectFullLambda createEffectFullLambda();

  /**
   * Returns a new object of class '<em>Data Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Value</em>'.
   * @generated
   */
  DataValue createDataValue();

  /**
   * Returns a new object of class '<em>Effect Full Data Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Data Value</em>'.
   * @generated
   */
  EffectFullDataValue createEffectFullDataValue();

  /**
   * Returns a new object of class '<em>Pure Lambda</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Lambda</em>'.
   * @generated
   */
  PureLambda createPureLambda();

  /**
   * Returns a new object of class '<em>Pure Prod Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Prod Value</em>'.
   * @generated
   */
  PureProdValue createPureProdValue();

  /**
   * Returns a new object of class '<em>Pure Sum Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pure Sum Value</em>'.
   * @generated
   */
  PureSumValue createPureSumValue();

  /**
   * Returns a new object of class '<em>Effect Full Prod Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Prod Value</em>'.
   * @generated
   */
  EffectFullProdValue createEffectFullProdValue();

  /**
   * Returns a new object of class '<em>Effect Full Sum Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effect Full Sum Value</em>'.
   * @generated
   */
  EffectFullSumValue createEffectFullSumValue();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FPMLPackage getFPMLPackage();

} //FPMLFactory
