/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Body Effect Full</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getFunctionBodyEffectFull()
 * @model
 * @generated
 */
public interface FunctionBodyEffectFull extends EObject
{
} // FunctionBodyEffectFull
