/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends ChainElement
{
} // Function
