/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Get Int Sdt In</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getGetIntSdtIn()
 * @model
 * @generated
 */
public interface GetIntSdtIn extends PrimitiveEffectFullFunction
{
} // GetIntSdtIn
