/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IO Pure Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.IOPureFunction#getPureFunction <em>Pure Function</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getIOPureFunction()
 * @model
 * @generated
 */
public interface IOPureFunction extends EffectFullExpression
{
  /**
   * Returns the value of the '<em><b>Pure Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pure Function</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pure Function</em>' reference.
   * @see #setPureFunction(PureFunction)
   * @see it.unibo.fPML.FPMLPackage#getIOPureFunction_PureFunction()
   * @model
   * @generated
   */
  PureFunction getPureFunction();

  /**
   * Sets the value of the '{@link it.unibo.fPML.IOPureFunction#getPureFunction <em>Pure Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pure Function</em>' reference.
   * @see #getPureFunction()
   * @generated
   */
  void setPureFunction(PureFunction value);

} // IOPureFunction
