/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lift Pure Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.LiftPureFunction#getFunctionRef <em>Function Ref</em>}</li>
 *   <li>{@link it.unibo.fPML.LiftPureFunction#getFunctionPrimitive <em>Function Primitive</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getLiftPureFunction()
 * @model
 * @generated
 */
public interface LiftPureFunction extends PrimitiveEffectFullFunction
{
  /**
   * Returns the value of the '<em><b>Function Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Ref</em>' reference.
   * @see #setFunctionRef(PureFunction)
   * @see it.unibo.fPML.FPMLPackage#getLiftPureFunction_FunctionRef()
   * @model
   * @generated
   */
  PureFunction getFunctionRef();

  /**
   * Sets the value of the '{@link it.unibo.fPML.LiftPureFunction#getFunctionRef <em>Function Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Ref</em>' reference.
   * @see #getFunctionRef()
   * @generated
   */
  void setFunctionRef(PureFunction value);

  /**
   * Returns the value of the '<em><b>Function Primitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Primitive</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Primitive</em>' containment reference.
   * @see #setFunctionPrimitive(PrimitivePureFunction)
   * @see it.unibo.fPML.FPMLPackage#getLiftPureFunction_FunctionPrimitive()
   * @model containment="true"
   * @generated
   */
  PrimitivePureFunction getFunctionPrimitive();

  /**
   * Sets the value of the '{@link it.unibo.fPML.LiftPureFunction#getFunctionPrimitive <em>Function Primitive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Primitive</em>' containment reference.
   * @see #getFunctionPrimitive()
   * @generated
   */
  void setFunctionPrimitive(PrimitivePureFunction value);

} // LiftPureFunction
