/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Major Equals</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getMajorEquals()
 * @model
 * @generated
 */
public interface MajorEquals extends PrimitivePureFunction
{
} // MajorEquals
