/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pure Either If</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.PureEitherIf#getThen <em>Then</em>}</li>
 *   <li>{@link it.unibo.fPML.PureEitherIf#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see it.unibo.fPML.FPMLPackage#getPureEitherIf()
 * @model
 * @generated
 */
public interface PureEitherIf extends PrimitivePureFunction
{
  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(PureIfBody)
   * @see it.unibo.fPML.FPMLPackage#getPureEitherIf_Then()
   * @model containment="true"
   * @generated
   */
  PureIfBody getThen();

  /**
   * Sets the value of the '{@link it.unibo.fPML.PureEitherIf#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(PureIfBody value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(PureIfBody)
   * @see it.unibo.fPML.FPMLPackage#getPureEitherIf_Else()
   * @model containment="true"
   * @generated
   */
  PureIfBody getElse();

  /**
   * Sets the value of the '{@link it.unibo.fPML.PureEitherIf#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(PureIfBody value);

} // PureEitherIf
