/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getTime()
 * @model
 * @generated
 */
public interface Time extends PrimitiveEffectFullValue
{
} // Time
