/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Void Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.fPML.FPMLPackage#getVoidType()
 * @model
 * @generated
 */
public interface VoidType extends EffectFullType
{
} // VoidType
