/**
 * generated by Xtext 2.9.2
 */
package it.unibo.generator;

import it.unibo.generator.DataGenerator;
import it.unibo.generator.EffectFullFunctionGenerator;
import it.unibo.generator.PureFunctionGenerator;
import it.unibo.generator.ValueGenerator;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FPMLGenerator extends AbstractGenerator {
  private final String basePackage = "it/unibo/";
  
  private final static String basePackageJava = "it.unibo.";
  
  private final PureFunctionGenerator pureFunctionGenerator = new PureFunctionGenerator();
  
  private final EffectFullFunctionGenerator effectFullFunctionGenerator = new EffectFullFunctionGenerator();
  
  private final DataGenerator dataGenerator = new DataGenerator();
  
  private final ValueGenerator valueGenerator = new ValueGenerator();
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from Object to CharSequence");
  }
  
  public static String getBasePackageJava() {
    return FPMLGenerator.basePackageJava;
  }
}
