/*
 * generated by Xtext 2.10.0
 */
package it.unibo.serializer;

import com.google.inject.Inject;
import it.unibo.fPML.AdditionalEffectFullArgument;
import it.unibo.fPML.AdditionalPureArgument;
import it.unibo.fPML.ApplyF;
import it.unibo.fPML.ApplyFFactor;
import it.unibo.fPML.ApplyFIO;
import it.unibo.fPML.ApplyFIOFactor;
import it.unibo.fPML.BoolToString;
import it.unibo.fPML.BooleanType;
import it.unibo.fPML.CompositionFunctionBodyEffect;
import it.unibo.fPML.CompositionFunctionBodyEffectFullFactor;
import it.unibo.fPML.CompositionFunctionBodyPure;
import it.unibo.fPML.CompositionFunctionBodyPureFactor;
import it.unibo.fPML.DataType;
import it.unibo.fPML.DataValue;
import it.unibo.fPML.EffectFullAlgebraicType;
import it.unibo.fPML.EffectFullArgument;
import it.unibo.fPML.EffectFullBlock;
import it.unibo.fPML.EffectFullData;
import it.unibo.fPML.EffectFullDataBlock;
import it.unibo.fPML.EffectFullDataType;
import it.unibo.fPML.EffectFullDataValue;
import it.unibo.fPML.EffectFullEitherIf;
import it.unibo.fPML.EffectFullExpressionAndEffectFullFunctionReference;
import it.unibo.fPML.EffectFullFunctionBlock;
import it.unibo.fPML.EffectFullFunctionDefinition;
import it.unibo.fPML.EffectFullFunctionType;
import it.unibo.fPML.EffectFullIf;
import it.unibo.fPML.EffectFullIfBody;
import it.unibo.fPML.EffectFullLambda;
import it.unibo.fPML.EffectFullProdTypeFactor;
import it.unibo.fPML.EffectFullProdValue;
import it.unibo.fPML.EffectFullReturn;
import it.unibo.fPML.EffectFullSumTypeFactor;
import it.unibo.fPML.EffectFullSumValue;
import it.unibo.fPML.EffectFullValue;
import it.unibo.fPML.EffectFullValueBlock;
import it.unibo.fPML.EffectFullValueRef;
import it.unibo.fPML.EmptyFunctionBody;
import it.unibo.fPML.Equals;
import it.unibo.fPML.ExtractEffectFull;
import it.unibo.fPML.ExtractPure;
import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.GetIntStdIn;
import it.unibo.fPML.GetLineStdIn;
import it.unibo.fPML.IOEffectFullExpression;
import it.unibo.fPML.IOEffectFullFunction;
import it.unibo.fPML.IOExpression;
import it.unibo.fPML.IOPureFunction;
import it.unibo.fPML.IOType;
import it.unibo.fPML.IntPow;
import it.unibo.fPML.IntToString;
import it.unibo.fPML.IntegerType;
import it.unibo.fPML.IsLeftEffectFull;
import it.unibo.fPML.IsLeftPure;
import it.unibo.fPML.IsRightEffectFull;
import it.unibo.fPML.IsRightPure;
import it.unibo.fPML.LeftAlgebraic;
import it.unibo.fPML.LeftAlgebraicIO;
import it.unibo.fPML.LiftEffectFullFunction;
import it.unibo.fPML.LiftPureFunction;
import it.unibo.fPML.LogicAnd;
import it.unibo.fPML.LogicNot;
import it.unibo.fPML.LogicOr;
import it.unibo.fPML.MainFunc;
import it.unibo.fPML.Major;
import it.unibo.fPML.MajorEquals;
import it.unibo.fPML.Minor;
import it.unibo.fPML.MinorEquals;
import it.unibo.fPML.Minus;
import it.unibo.fPML.Mod;
import it.unibo.fPML.Model;
import it.unibo.fPML.Plus;
import it.unibo.fPML.Print;
import it.unibo.fPML.PureAlgebraicType;
import it.unibo.fPML.PureArgument;
import it.unibo.fPML.PureBlock;
import it.unibo.fPML.PureData;
import it.unibo.fPML.PureDataBlock;
import it.unibo.fPML.PureEitherIf;
import it.unibo.fPML.PureExpressionAndPureFunctionReference;
import it.unibo.fPML.PureFunctionBlock;
import it.unibo.fPML.PureFunctionDefinition;
import it.unibo.fPML.PureFunctionType;
import it.unibo.fPML.PureIf;
import it.unibo.fPML.PureIfBody;
import it.unibo.fPML.PureLambda;
import it.unibo.fPML.PureProdTypeFactor;
import it.unibo.fPML.PureProdValue;
import it.unibo.fPML.PureReturn;
import it.unibo.fPML.PureSumTypeFactor;
import it.unibo.fPML.PureSumValue;
import it.unibo.fPML.PureValue;
import it.unibo.fPML.PureValueBlock;
import it.unibo.fPML.PureValueRef;
import it.unibo.fPML.Random;
import it.unibo.fPML.RightAlgebraic;
import it.unibo.fPML.RightAlgebraicIO;
import it.unibo.fPML.StringType;
import it.unibo.fPML.Time;
import it.unibo.fPML.Times;
import it.unibo.fPML.UnitType;
import it.unibo.fPML.VoidType;
import it.unibo.services.FPMLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class FPMLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private FPMLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FPMLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FPMLPackage.ADDITIONAL_EFFECT_FULL_ARGUMENT:
				sequence_AdditionalEffectFullArgument(context, (AdditionalEffectFullArgument) semanticObject); 
				return; 
			case FPMLPackage.ADDITIONAL_PURE_ARGUMENT:
				sequence_AdditionalPureArgument(context, (AdditionalPureArgument) semanticObject); 
				return; 
			case FPMLPackage.APPLY_F:
				sequence_ApplyF(context, (ApplyF) semanticObject); 
				return; 
			case FPMLPackage.APPLY_FFACTOR:
				sequence_ApplyFFactor(context, (ApplyFFactor) semanticObject); 
				return; 
			case FPMLPackage.APPLY_FIO:
				sequence_ApplyFIO(context, (ApplyFIO) semanticObject); 
				return; 
			case FPMLPackage.APPLY_FIO_FACTOR:
				sequence_ApplyFIOFactor(context, (ApplyFIOFactor) semanticObject); 
				return; 
			case FPMLPackage.BOOL_TO_STRING:
				sequence_BoolToString(context, (BoolToString) semanticObject); 
				return; 
			case FPMLPackage.BOOLEAN_TYPE:
				if (rule == grammarAccess.getValueTypeRule()
						|| rule == grammarAccess.getTypeRule()
						|| rule == grammarAccess.getBooleanTypeRule()) {
					sequence_BooleanType(context, (BooleanType) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getFunctionRule()
						|| rule == grammarAccess.getPureFunctionRule()
						|| rule == grammarAccess.getExpressionRule()
						|| rule == grammarAccess.getBooleanValueRule()) {
					sequence_BooleanValue(context, (BooleanType) semanticObject); 
					return; 
				}
				else break;
			case FPMLPackage.COMPOSITION_FUNCTION_BODY_EFFECT:
				sequence_CompositionFunctionBodyEffect(context, (CompositionFunctionBodyEffect) semanticObject); 
				return; 
			case FPMLPackage.COMPOSITION_FUNCTION_BODY_EFFECT_FULL_FACTOR:
				sequence_CompositionFunctionBodyEffectFullFactor(context, (CompositionFunctionBodyEffectFullFactor) semanticObject); 
				return; 
			case FPMLPackage.COMPOSITION_FUNCTION_BODY_PURE:
				sequence_CompositionFunctionBodyPure(context, (CompositionFunctionBodyPure) semanticObject); 
				return; 
			case FPMLPackage.COMPOSITION_FUNCTION_BODY_PURE_FACTOR:
				sequence_CompositionFunctionBodyPureFactor(context, (CompositionFunctionBodyPureFactor) semanticObject); 
				return; 
			case FPMLPackage.DATA_TYPE:
				sequence_DataType(context, (DataType) semanticObject); 
				return; 
			case FPMLPackage.DATA_VALUE:
				sequence_DataValue(context, (DataValue) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_ALGEBRAIC_TYPE:
				sequence_EffectFullAlgebraicType(context, (EffectFullAlgebraicType) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_ARGUMENT:
				sequence_EffectFullArgument(context, (EffectFullArgument) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_BLOCK:
				sequence_EffectFullBlock(context, (EffectFullBlock) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_DATA:
				sequence_EffectFullData(context, (EffectFullData) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_DATA_BLOCK:
				sequence_EffectFullDataBlock(context, (EffectFullDataBlock) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_DATA_TYPE:
				sequence_EffectFullDataType(context, (EffectFullDataType) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_DATA_VALUE:
				sequence_EffectFullDataValue(context, (EffectFullDataValue) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_EITHER_IF:
				sequence_EffectFullEitherIf(context, (EffectFullEitherIf) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_EXPRESSION_AND_EFFECT_FULL_FUNCTION_REFERENCE:
				sequence_EffectFullExpressionAndEffectFullFunctionReference(context, (EffectFullExpressionAndEffectFullFunctionReference) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_FUNCTION_BLOCK:
				sequence_EffectFullFunctionBlock(context, (EffectFullFunctionBlock) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_FUNCTION_DEFINITION:
				sequence_EffectFullFunctionDefinition(context, (EffectFullFunctionDefinition) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_FUNCTION_TYPE:
				if (rule == grammarAccess.getTypeRule()
						|| rule == grammarAccess.getEffectFullTypeRule()
						|| rule == grammarAccess.getEffectFullFunctionTypeRule()) {
					sequence_EffectFullFunctionType(context, (EffectFullFunctionType) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getEffectFullBodyContentRule()
						|| rule == grammarAccess.getEffectFullExpressionRule()
						|| rule == grammarAccess.getEffectFullFunctionValueRule()) {
					sequence_EffectFullFunctionValue(context, (EffectFullFunctionType) semanticObject); 
					return; 
				}
				else break;
			case FPMLPackage.EFFECT_FULL_IF:
				sequence_EffectFullIf(context, (EffectFullIf) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_IF_BODY:
				sequence_EffectFullIfBody(context, (EffectFullIfBody) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_LAMBDA:
				sequence_EffectFullLambda(context, (EffectFullLambda) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_PROD_TYPE_FACTOR:
				sequence_EffectFullProdTypeFactor(context, (EffectFullProdTypeFactor) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_PROD_VALUE:
				sequence_EffectFullProdValue(context, (EffectFullProdValue) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_RETURN:
				sequence_EffectFullReturn(context, (EffectFullReturn) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_SUM_TYPE_FACTOR:
				sequence_EffectFullSumTypeFactor(context, (EffectFullSumTypeFactor) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_SUM_VALUE:
				sequence_EffectFullSumValue(context, (EffectFullSumValue) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_VALUE:
				sequence_EffectFullValue(context, (EffectFullValue) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_VALUE_BLOCK:
				sequence_EffectFullValueBlock(context, (EffectFullValueBlock) semanticObject); 
				return; 
			case FPMLPackage.EFFECT_FULL_VALUE_REF:
				sequence_EffectFullValueRef(context, (EffectFullValueRef) semanticObject); 
				return; 
			case FPMLPackage.EMPTY_FUNCTION_BODY:
				sequence_EmptyFunctionBody(context, (EmptyFunctionBody) semanticObject); 
				return; 
			case FPMLPackage.EQUALS:
				sequence_Equals(context, (Equals) semanticObject); 
				return; 
			case FPMLPackage.EXTRACT_EFFECT_FULL:
				sequence_ExtractEffectFull(context, (ExtractEffectFull) semanticObject); 
				return; 
			case FPMLPackage.EXTRACT_PURE:
				sequence_ExtractPure(context, (ExtractPure) semanticObject); 
				return; 
			case FPMLPackage.GET_INT_STD_IN:
				sequence_GetIntSdtIn(context, (GetIntStdIn) semanticObject); 
				return; 
			case FPMLPackage.GET_LINE_STD_IN:
				sequence_GetLineStdIn(context, (GetLineStdIn) semanticObject); 
				return; 
			case FPMLPackage.IO_EFFECT_FULL_EXPRESSION:
				sequence_EffectFullExpression(context, (IOEffectFullExpression) semanticObject); 
				return; 
			case FPMLPackage.IO_EFFECT_FULL_FUNCTION:
				sequence_EffectFullExpression(context, (IOEffectFullFunction) semanticObject); 
				return; 
			case FPMLPackage.IO_EXPRESSION:
				sequence_EffectFullExpression(context, (IOExpression) semanticObject); 
				return; 
			case FPMLPackage.IO_PURE_FUNCTION:
				sequence_EffectFullExpression(context, (IOPureFunction) semanticObject); 
				return; 
			case FPMLPackage.IO_TYPE:
				sequence_IOType(context, (IOType) semanticObject); 
				return; 
			case FPMLPackage.INT_POW:
				sequence_IntPow(context, (IntPow) semanticObject); 
				return; 
			case FPMLPackage.INT_TO_STRING:
				sequence_IntToString(context, (IntToString) semanticObject); 
				return; 
			case FPMLPackage.INTEGER_TYPE:
				if (rule == grammarAccess.getFunctionRule()
						|| rule == grammarAccess.getPureFunctionRule()
						|| rule == grammarAccess.getExpressionRule()
						|| rule == grammarAccess.getIntValueRule()) {
					sequence_IntValue(context, (IntegerType) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getValueTypeRule()
						|| rule == grammarAccess.getTypeRule()
						|| rule == grammarAccess.getIntegerTypeRule()) {
					sequence_IntegerType(context, (IntegerType) semanticObject); 
					return; 
				}
				else break;
			case FPMLPackage.IS_LEFT_EFFECT_FULL:
				sequence_IsLeftEffectFull(context, (IsLeftEffectFull) semanticObject); 
				return; 
			case FPMLPackage.IS_LEFT_PURE:
				sequence_IsLeftPure(context, (IsLeftPure) semanticObject); 
				return; 
			case FPMLPackage.IS_RIGHT_EFFECT_FULL:
				sequence_IsRightEffectFull(context, (IsRightEffectFull) semanticObject); 
				return; 
			case FPMLPackage.IS_RIGHT_PURE:
				sequence_IsRightPure(context, (IsRightPure) semanticObject); 
				return; 
			case FPMLPackage.LEFT_ALGEBRAIC:
				sequence_LeftAlgebraic(context, (LeftAlgebraic) semanticObject); 
				return; 
			case FPMLPackage.LEFT_ALGEBRAIC_IO:
				sequence_LeftAlgebraicIO(context, (LeftAlgebraicIO) semanticObject); 
				return; 
			case FPMLPackage.LIFT_EFFECT_FULL_FUNCTION:
				sequence_LiftEffectFullFunction(context, (LiftEffectFullFunction) semanticObject); 
				return; 
			case FPMLPackage.LIFT_PURE_FUNCTION:
				sequence_LiftPureFunction(context, (LiftPureFunction) semanticObject); 
				return; 
			case FPMLPackage.LOGIC_AND:
				sequence_LogicAnd(context, (LogicAnd) semanticObject); 
				return; 
			case FPMLPackage.LOGIC_NOT:
				sequence_LogicNot(context, (LogicNot) semanticObject); 
				return; 
			case FPMLPackage.LOGIC_OR:
				sequence_LogicOr(context, (LogicOr) semanticObject); 
				return; 
			case FPMLPackage.MAIN_FUNC:
				sequence_MainFunc(context, (MainFunc) semanticObject); 
				return; 
			case FPMLPackage.MAJOR:
				sequence_Major(context, (Major) semanticObject); 
				return; 
			case FPMLPackage.MAJOR_EQUALS:
				sequence_MajorEquals(context, (MajorEquals) semanticObject); 
				return; 
			case FPMLPackage.MINOR:
				sequence_Minor(context, (Minor) semanticObject); 
				return; 
			case FPMLPackage.MINOR_EQUALS:
				sequence_MinorEquals(context, (MinorEquals) semanticObject); 
				return; 
			case FPMLPackage.MINUS:
				sequence_Minus(context, (Minus) semanticObject); 
				return; 
			case FPMLPackage.MOD:
				sequence_Mod(context, (Mod) semanticObject); 
				return; 
			case FPMLPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case FPMLPackage.PLUS:
				sequence_Plus(context, (Plus) semanticObject); 
				return; 
			case FPMLPackage.PRINT:
				sequence_Print(context, (Print) semanticObject); 
				return; 
			case FPMLPackage.PURE_ALGEBRAIC_TYPE:
				sequence_PureAlgebraicType(context, (PureAlgebraicType) semanticObject); 
				return; 
			case FPMLPackage.PURE_ARGUMENT:
				sequence_PureArgument(context, (PureArgument) semanticObject); 
				return; 
			case FPMLPackage.PURE_BLOCK:
				sequence_PureBlock(context, (PureBlock) semanticObject); 
				return; 
			case FPMLPackage.PURE_DATA:
				sequence_PureData(context, (PureData) semanticObject); 
				return; 
			case FPMLPackage.PURE_DATA_BLOCK:
				sequence_PureDataBlock(context, (PureDataBlock) semanticObject); 
				return; 
			case FPMLPackage.PURE_EITHER_IF:
				sequence_PureEitherIf(context, (PureEitherIf) semanticObject); 
				return; 
			case FPMLPackage.PURE_EXPRESSION_AND_PURE_FUNCTION_REFERENCE:
				sequence_PureExpressionAndPureFunctionReference(context, (PureExpressionAndPureFunctionReference) semanticObject); 
				return; 
			case FPMLPackage.PURE_FUNCTION_BLOCK:
				sequence_PureFunctionBlock(context, (PureFunctionBlock) semanticObject); 
				return; 
			case FPMLPackage.PURE_FUNCTION_DEFINITION:
				sequence_PureFunctionDefinition(context, (PureFunctionDefinition) semanticObject); 
				return; 
			case FPMLPackage.PURE_FUNCTION_TYPE:
				if (rule == grammarAccess.getFunctionRule()
						|| rule == grammarAccess.getPureFunctionRule()
						|| rule == grammarAccess.getExpressionRule()
						|| rule == grammarAccess.getFunctionValueRule()) {
					sequence_FunctionValue(context, (PureFunctionType) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getValueTypeRule()
						|| rule == grammarAccess.getTypeRule()
						|| rule == grammarAccess.getPureFunctionTypeRule()) {
					sequence_PureFunctionType(context, (PureFunctionType) semanticObject); 
					return; 
				}
				else break;
			case FPMLPackage.PURE_IF:
				sequence_PureIf(context, (PureIf) semanticObject); 
				return; 
			case FPMLPackage.PURE_IF_BODY:
				sequence_PureIfBody(context, (PureIfBody) semanticObject); 
				return; 
			case FPMLPackage.PURE_LAMBDA:
				sequence_PureLambda(context, (PureLambda) semanticObject); 
				return; 
			case FPMLPackage.PURE_PROD_TYPE_FACTOR:
				sequence_PureProdTypeFactor(context, (PureProdTypeFactor) semanticObject); 
				return; 
			case FPMLPackage.PURE_PROD_VALUE:
				sequence_PureProdValue(context, (PureProdValue) semanticObject); 
				return; 
			case FPMLPackage.PURE_RETURN:
				sequence_PureReturn(context, (PureReturn) semanticObject); 
				return; 
			case FPMLPackage.PURE_SUM_TYPE_FACTOR:
				sequence_PureSumTypeFactor(context, (PureSumTypeFactor) semanticObject); 
				return; 
			case FPMLPackage.PURE_SUM_VALUE:
				sequence_PureSumValue(context, (PureSumValue) semanticObject); 
				return; 
			case FPMLPackage.PURE_VALUE:
				sequence_PureValue(context, (PureValue) semanticObject); 
				return; 
			case FPMLPackage.PURE_VALUE_BLOCK:
				sequence_PureValueBlock(context, (PureValueBlock) semanticObject); 
				return; 
			case FPMLPackage.PURE_VALUE_REF:
				sequence_PureValueRef(context, (PureValueRef) semanticObject); 
				return; 
			case FPMLPackage.RANDOM:
				sequence_Random(context, (Random) semanticObject); 
				return; 
			case FPMLPackage.RIGHT_ALGEBRAIC:
				sequence_RightAlgebraic(context, (RightAlgebraic) semanticObject); 
				return; 
			case FPMLPackage.RIGHT_ALGEBRAIC_IO:
				sequence_RightAlgebraicIO(context, (RightAlgebraicIO) semanticObject); 
				return; 
			case FPMLPackage.STRING_TYPE:
				if (rule == grammarAccess.getValueTypeRule()
						|| rule == grammarAccess.getTypeRule()
						|| rule == grammarAccess.getStringTypeRule()) {
					sequence_StringType(context, (StringType) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getFunctionRule()
						|| rule == grammarAccess.getPureFunctionRule()
						|| rule == grammarAccess.getExpressionRule()
						|| rule == grammarAccess.getStringValueRule()) {
					sequence_StringValue(context, (StringType) semanticObject); 
					return; 
				}
				else break;
			case FPMLPackage.TIME:
				sequence_Time(context, (Time) semanticObject); 
				return; 
			case FPMLPackage.TIMES:
				sequence_Times(context, (Times) semanticObject); 
				return; 
			case FPMLPackage.UNIT_TYPE:
				if (rule == grammarAccess.getValueTypeRule()
						|| rule == grammarAccess.getTypeRule()
						|| rule == grammarAccess.getUnitTypeRule()) {
					sequence_UnitType(context, (UnitType) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getFunctionRule()
						|| rule == grammarAccess.getPureFunctionRule()
						|| rule == grammarAccess.getUnitValueRule()
						|| rule == grammarAccess.getExpressionRule()) {
					sequence_UnitValue(context, (UnitType) semanticObject); 
					return; 
				}
				else break;
			case FPMLPackage.VOID_TYPE:
				sequence_VoidType(context, (VoidType) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AdditionalEffectFullArgument returns AdditionalEffectFullArgument
	 *
	 * Constraint:
	 *     arg2=Argument
	 */
	protected void sequence_AdditionalEffectFullArgument(ISerializationContext context, AdditionalEffectFullArgument semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.ADDITIONAL_EFFECT_FULL_ARGUMENT__ARG2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.ADDITIONAL_EFFECT_FULL_ARGUMENT__ARG2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAdditionalEffectFullArgumentAccess().getArg2ArgumentParserRuleCall_0(), semanticObject.getArg2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AdditionalPureArgument returns AdditionalPureArgument
	 *
	 * Constraint:
	 *     arg2=PureArgument
	 */
	protected void sequence_AdditionalPureArgument(ISerializationContext context, AdditionalPureArgument semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.ADDITIONAL_PURE_ARGUMENT__ARG2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.ADDITIONAL_PURE_ARGUMENT__ARG2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAdditionalPureArgumentAccess().getArg2PureArgumentParserRuleCall_0(), semanticObject.getArg2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ApplyFFactor returns ApplyFFactor
	 *
	 * Constraint:
	 *     (valueReference=[PureFunction|ID] | valueExpression=Expression)
	 */
	protected void sequence_ApplyFFactor(ISerializationContext context, ApplyFFactor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ApplyFIOFactor returns ApplyFIOFactor
	 *
	 * Constraint:
	 *     (valueReference=[EffectFullFunction|ID] | valuePrimitive=EffectFullPrimitive | valueExpression=EffectFullExpression)
	 */
	protected void sequence_ApplyFIOFactor(ISerializationContext context, ApplyFIOFactor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns ApplyFIO
	 *     EffectFullFunction returns ApplyFIO
	 *     PrimitiveFunction returns ApplyFIO
	 *     EffectFullPrimitive returns ApplyFIO
	 *     EffectFullBodyContent returns ApplyFIO
	 *     PrimitiveEffectFullFunction returns ApplyFIO
	 *     ApplyFIO returns ApplyFIO
	 *
	 * Constraint:
	 *     (functionType=EffectFullFunctionType value=ApplyFIOFactor)
	 */
	protected void sequence_ApplyFIO(ISerializationContext context, ApplyFIO semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.APPLY_FIO__FUNCTION_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.APPLY_FIO__FUNCTION_TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.APPLY_FIO__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.APPLY_FIO__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getApplyFIOAccess().getFunctionTypeEffectFullFunctionTypeParserRuleCall_2_0(), semanticObject.getFunctionType());
		feeder.accept(grammarAccess.getApplyFIOAccess().getValueApplyFIOFactorParserRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns ApplyF
	 *     PureFunction returns ApplyF
	 *     PrimitiveFunction returns ApplyF
	 *     PrimitivePureFunction returns ApplyF
	 *     ApplyF returns ApplyF
	 *
	 * Constraint:
	 *     (functionType=PureFunctionType value=ApplyFFactor)
	 */
	protected void sequence_ApplyF(ISerializationContext context, ApplyF semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.APPLY_F__FUNCTION_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.APPLY_F__FUNCTION_TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.APPLY_F__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.APPLY_F__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getApplyFAccess().getFunctionTypePureFunctionTypeParserRuleCall_2_0(), semanticObject.getFunctionType());
		feeder.accept(grammarAccess.getApplyFAccess().getValueApplyFFactorParserRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns BoolToString
	 *     PureFunction returns BoolToString
	 *     PrimitiveFunction returns BoolToString
	 *     PrimitivePureFunction returns BoolToString
	 *     BoolToString returns BoolToString
	 *
	 * Constraint:
	 *     {BoolToString}
	 */
	protected void sequence_BoolToString(ISerializationContext context, BoolToString semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns BooleanType
	 *     Type returns BooleanType
	 *     BooleanType returns BooleanType
	 *
	 * Constraint:
	 *     type='boolean'
	 */
	protected void sequence_BooleanType(ISerializationContext context, BooleanType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.BOOLEAN_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.BOOLEAN_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBooleanTypeAccess().getTypeBooleanKeyword_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns BooleanType
	 *     PureFunction returns BooleanType
	 *     Expression returns BooleanType
	 *     BooleanValue returns BooleanType
	 *
	 * Constraint:
	 *     value=BOOLEAN
	 */
	protected void sequence_BooleanValue(ISerializationContext context, BooleanType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.BOOLEAN_TYPE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.BOOLEAN_TYPE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBooleanValueAccess().getValueBOOLEANTerminalRuleCall_1_0(), semanticObject.isValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     CompositionFunctionBodyEffectFullFactor returns CompositionFunctionBodyEffectFullFactor
	 *
	 * Constraint:
	 *     (referenceElement=[EffectFullFunction|ID] | primitiveElement=EffectFullPrimitive | expressionElement=EffectFullExpression)
	 */
	protected void sequence_CompositionFunctionBodyEffectFullFactor(ISerializationContext context, CompositionFunctionBodyEffectFullFactor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     FunctionBodyEffectFull returns CompositionFunctionBodyEffect
	 *     CompositionFunctionBodyEffect returns CompositionFunctionBodyEffect
	 *
	 * Constraint:
	 *     (
	 *         (referenceElement=[EffectFullFunction|ID] functionChain+=CompositionFunctionBodyEffectFullFactor+) | 
	 *         (primitiveElement=EffectFullPrimitive functionChain+=CompositionFunctionBodyEffectFullFactor+) | 
	 *         (expressionElement=EffectFullExpression functionChain+=CompositionFunctionBodyEffectFullFactor+)
	 *     )
	 */
	protected void sequence_CompositionFunctionBodyEffect(ISerializationContext context, CompositionFunctionBodyEffect semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     CompositionFunctionBodyPureFactor returns CompositionFunctionBodyPureFactor
	 *
	 * Constraint:
	 *     (referenceElement=[PureFunction|ID] | primitiveElement=PrimitivePureFunction | expressionElement=Expression)
	 */
	protected void sequence_CompositionFunctionBodyPureFactor(ISerializationContext context, CompositionFunctionBodyPureFactor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     FunctionBodyPure returns CompositionFunctionBodyPure
	 *     CompositionFunctionBodyPure returns CompositionFunctionBodyPure
	 *
	 * Constraint:
	 *     (
	 *         (referenceElement=[PureFunction|ID] functionChain+=CompositionFunctionBodyPureFactor+) | 
	 *         (primitiveElement=PrimitivePureFunction functionChain+=CompositionFunctionBodyPureFactor+) | 
	 *         (expressionElement=Expression functionChain+=CompositionFunctionBodyPureFactor+)
	 *     )
	 */
	protected void sequence_CompositionFunctionBodyPure(ISerializationContext context, CompositionFunctionBodyPure semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns DataType
	 *     Type returns DataType
	 *     DataType returns DataType
	 *
	 * Constraint:
	 *     type=[PureData|ID]
	 */
	protected void sequence_DataType(ISerializationContext context, DataType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.DATA_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.DATA_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDataTypeAccess().getTypePureDataIDTerminalRuleCall_2_0_1(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns DataValue
	 *     PureFunction returns DataValue
	 *     Expression returns DataValue
	 *     DataValue returns DataValue
	 *
	 * Constraint:
	 *     (type=[PureData|ID] value=PureExpressionAndPureFunctionReference)
	 */
	protected void sequence_DataValue(ISerializationContext context, DataValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.DATA_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.DATA_TYPE__TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.DATA_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.DATA_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDataValueAccess().getTypePureDataIDTerminalRuleCall_1_0_1(), semanticObject.getType());
		feeder.accept(grammarAccess.getDataValueAccess().getValuePureExpressionAndPureFunctionReferenceParserRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns EffectFullAlgebraicType
	 *     EffectFullType returns EffectFullAlgebraicType
	 *     EffectFullAlgebraicType returns EffectFullAlgebraicType
	 *
	 * Constraint:
	 *     (effectFullAdtElement1=Type (effectFullAdtElement2=EffectFullSumTypeFactor | effectFullAdtElement2=EffectFullProdTypeFactor))
	 */
	protected void sequence_EffectFullAlgebraicType(ISerializationContext context, EffectFullAlgebraicType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns EffectFullArgument
	 *     EffectFullFunction returns EffectFullArgument
	 *     EffectFullBodyContent returns EffectFullArgument
	 *     Argument returns EffectFullArgument
	 *     EffectFullArgument returns EffectFullArgument
	 *
	 * Constraint:
	 *     (type=EffectFullType name=ID)
	 */
	protected void sequence_EffectFullArgument(ISerializationContext context, EffectFullArgument semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_ARGUMENT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_ARGUMENT__TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_ARGUMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_ARGUMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullArgumentAccess().getTypeEffectFullTypeParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getEffectFullArgumentAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBlock returns EffectFullBlock
	 *
	 * Constraint:
	 *     (elements+=EffectFullDataBlock elements+=EffectFullFunctionBlock)
	 */
	protected void sequence_EffectFullBlock(ISerializationContext context, EffectFullBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullDataBlock returns EffectFullDataBlock
	 *
	 * Constraint:
	 *     (elements+=EffectFullData* value=EffectFullValueBlock)
	 */
	protected void sequence_EffectFullDataBlock(ISerializationContext context, EffectFullDataBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns EffectFullDataType
	 *     EffectFullType returns EffectFullDataType
	 *     EffectFullDataType returns EffectFullDataType
	 *
	 * Constraint:
	 *     type=[EffectFullData|ID]
	 */
	protected void sequence_EffectFullDataType(ISerializationContext context, EffectFullDataType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullDataTypeAccess().getTypeEffectFullDataIDTerminalRuleCall_2_0_1(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns EffectFullDataValue
	 *     EffectFullExpression returns EffectFullDataValue
	 *     EffectFullDataValue returns EffectFullDataValue
	 *
	 * Constraint:
	 *     (type=[EffectFullData|ID] value=EffectFullExpressionAndEffectFullFunctionReference)
	 */
	protected void sequence_EffectFullDataValue(ISerializationContext context, EffectFullDataValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA_TYPE__TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullDataValueAccess().getTypeEffectFullDataIDTerminalRuleCall_1_0_1(), semanticObject.getType());
		feeder.accept(grammarAccess.getEffectFullDataValueAccess().getValueEffectFullExpressionAndEffectFullFunctionReferenceParserRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullData returns EffectFullData
	 *
	 * Constraint:
	 *     (name=ID content=EffectFullType)
	 */
	protected void sequence_EffectFullData(ISerializationContext context, EffectFullData semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA__NAME));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA__CONTENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_DATA__CONTENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullDataAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getEffectFullDataAccess().getContentEffectFullTypeParserRuleCall_2_0(), semanticObject.getContent());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns EffectFullEitherIf
	 *     EffectFullFunction returns EffectFullEitherIf
	 *     PrimitiveFunction returns EffectFullEitherIf
	 *     EffectFullPrimitive returns EffectFullEitherIf
	 *     EffectFullBodyContent returns EffectFullEitherIf
	 *     PrimitiveEffectFullFunction returns EffectFullEitherIf
	 *     EffectFullEitherIf returns EffectFullEitherIf
	 *
	 * Constraint:
	 *     (then=EffectFullIfBody else=EffectFullIfBody)
	 */
	protected void sequence_EffectFullEitherIf(ISerializationContext context, EffectFullEitherIf semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_EITHER_IF__THEN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_EITHER_IF__THEN));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_EITHER_IF__ELSE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_EITHER_IF__ELSE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullEitherIfAccess().getThenEffectFullIfBodyParserRuleCall_4_0(), semanticObject.getThen());
		feeder.accept(grammarAccess.getEffectFullEitherIfAccess().getElseEffectFullIfBodyParserRuleCall_8_0(), semanticObject.getElse());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullExpressionAndEffectFullFunctionReference returns EffectFullExpressionAndEffectFullFunctionReference
	 *
	 * Constraint:
	 *     (prodAdtElementExpression=EffectFullExpression | prodAdtElementFunction=[EffectFullFunction|ID])
	 */
	protected void sequence_EffectFullExpressionAndEffectFullFunctionReference(ISerializationContext context, EffectFullExpressionAndEffectFullFunctionReference semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns IOEffectFullExpression
	 *     EffectFullExpression returns IOEffectFullExpression
	 *
	 * Constraint:
	 *     innerValue=EffectFullExpression
	 */
	protected void sequence_EffectFullExpression(ISerializationContext context, IOEffectFullExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IO_EFFECT_FULL_EXPRESSION__INNER_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IO_EFFECT_FULL_EXPRESSION__INNER_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullExpressionAccess().getInnerValueEffectFullExpressionParserRuleCall_0_3_0(), semanticObject.getInnerValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns IOEffectFullFunction
	 *     EffectFullExpression returns IOEffectFullFunction
	 *
	 * Constraint:
	 *     (effectFullFunction=[EffectFullFunction|ID] | effectFullPrimitive=PrimitiveEffectFullFunction)
	 */
	protected void sequence_EffectFullExpression(ISerializationContext context, IOEffectFullFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns IOExpression
	 *     EffectFullExpression returns IOExpression
	 *
	 * Constraint:
	 *     innerValue=Expression
	 */
	protected void sequence_EffectFullExpression(ISerializationContext context, IOExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IO_EXPRESSION__INNER_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IO_EXPRESSION__INNER_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullExpressionAccess().getInnerValueExpressionParserRuleCall_1_3_0(), semanticObject.getInnerValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns IOPureFunction
	 *     EffectFullExpression returns IOPureFunction
	 *
	 * Constraint:
	 *     (pureFunction=[PureFunction|ID] | purePrimitive=PrimitivePureFunction)
	 */
	protected void sequence_EffectFullExpression(ISerializationContext context, IOPureFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullFunctionBlock returns EffectFullFunctionBlock
	 *
	 * Constraint:
	 *     (features+=EffectFullFunctionDefinition* main=MainFunc)
	 */
	protected void sequence_EffectFullFunctionBlock(ISerializationContext context, EffectFullFunctionBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullFunctionDefinition returns EffectFullFunctionDefinition
	 *     Function returns EffectFullFunctionDefinition
	 *     EffectFullFunction returns EffectFullFunctionDefinition
	 *     EffectFullBodyContent returns EffectFullFunctionDefinition
	 *
	 * Constraint:
	 *     (returnType=IOType name=ID arg=Argument higherOrderArg=AdditionalEffectFullArgument? functionBody=FunctionBodyEffectFull)
	 */
	protected void sequence_EffectFullFunctionDefinition(ISerializationContext context, EffectFullFunctionDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns EffectFullFunctionType
	 *     EffectFullType returns EffectFullFunctionType
	 *     EffectFullFunctionType returns EffectFullFunctionType
	 *
	 * Constraint:
	 *     (argType=Type returnType=IOType)
	 */
	protected void sequence_EffectFullFunctionType(ISerializationContext context, EffectFullFunctionType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_TYPE__ARG_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_TYPE__ARG_TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_TYPE__RETURN_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_TYPE__RETURN_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullFunctionTypeAccess().getArgTypeTypeParserRuleCall_3_0(), semanticObject.getArgType());
		feeder.accept(grammarAccess.getEffectFullFunctionTypeAccess().getReturnTypeIOTypeParserRuleCall_5_0(), semanticObject.getReturnType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns EffectFullFunctionType
	 *     EffectFullExpression returns EffectFullFunctionType
	 *     EffectFullFunctionValue returns EffectFullFunctionType
	 *
	 * Constraint:
	 *     value=EffectFullLambda
	 */
	protected void sequence_EffectFullFunctionValue(ISerializationContext context, EffectFullFunctionType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_TYPE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_TYPE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullFunctionValueAccess().getValueEffectFullLambdaParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullIfBody returns EffectFullIfBody
	 *
	 * Constraint:
	 *     (functionReference=[EffectFullFunction|ID] | functionExpression=EffectFullExpression)
	 */
	protected void sequence_EffectFullIfBody(ISerializationContext context, EffectFullIfBody semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns EffectFullIf
	 *     EffectFullFunction returns EffectFullIf
	 *     PrimitiveFunction returns EffectFullIf
	 *     EffectFullPrimitive returns EffectFullIf
	 *     EffectFullBodyContent returns EffectFullIf
	 *     PrimitiveEffectFullFunction returns EffectFullIf
	 *     EffectFullIf returns EffectFullIf
	 *
	 * Constraint:
	 *     (then=EffectFullIfBody else=EffectFullIfBody)
	 */
	protected void sequence_EffectFullIf(ISerializationContext context, EffectFullIf semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_IF__THEN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_IF__THEN));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_IF__ELSE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_IF__ELSE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullIfAccess().getThenEffectFullIfBodyParserRuleCall_4_0(), semanticObject.getThen());
		feeder.accept(grammarAccess.getEffectFullIfAccess().getElseEffectFullIfBodyParserRuleCall_8_0(), semanticObject.getElse());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullLambda returns EffectFullLambda
	 *
	 * Constraint:
	 *     ((arg=Argument functionBody=CompositionFunctionBodyEffect) | functionBody=CompositionFunctionBodyEffect)
	 */
	protected void sequence_EffectFullLambda(ISerializationContext context, EffectFullLambda semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullProdTypeFactor returns EffectFullProdTypeFactor
	 *
	 * Constraint:
	 *     adtElement=Type
	 */
	protected void sequence_EffectFullProdTypeFactor(ISerializationContext context, EffectFullProdTypeFactor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_PROD_TYPE_FACTOR__ADT_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_PROD_TYPE_FACTOR__ADT_ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullProdTypeFactorAccess().getAdtElementTypeParserRuleCall_1_0(), semanticObject.getAdtElement());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns EffectFullProdValue
	 *     EffectFullExpression returns EffectFullProdValue
	 *     EffectFullProdValue returns EffectFullProdValue
	 *
	 * Constraint:
	 *     (prodAdtElement1=EffectFullExpressionAndEffectFullFunctionReference prodAdtElement2=EffectFullExpressionAndEffectFullFunctionReference)
	 */
	protected void sequence_EffectFullProdValue(ISerializationContext context, EffectFullProdValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_PROD_VALUE__PROD_ADT_ELEMENT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_PROD_VALUE__PROD_ADT_ELEMENT1));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_PROD_VALUE__PROD_ADT_ELEMENT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_PROD_VALUE__PROD_ADT_ELEMENT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullProdValueAccess().getProdAdtElement1EffectFullExpressionAndEffectFullFunctionReferenceParserRuleCall_2_0(), semanticObject.getProdAdtElement1());
		feeder.accept(grammarAccess.getEffectFullProdValueAccess().getProdAdtElement2EffectFullExpressionAndEffectFullFunctionReferenceParserRuleCall_4_0(), semanticObject.getProdAdtElement2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns EffectFullReturn
	 *     EffectFullFunction returns EffectFullReturn
	 *     PrimitiveFunction returns EffectFullReturn
	 *     EffectFullPrimitive returns EffectFullReturn
	 *     EffectFullBodyContent returns EffectFullReturn
	 *     PrimitiveEffectFullFunction returns EffectFullReturn
	 *     EffectFullReturn returns EffectFullReturn
	 *
	 * Constraint:
	 *     type=Type
	 */
	protected void sequence_EffectFullReturn(ISerializationContext context, EffectFullReturn semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_RETURN__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_RETURN__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullReturnAccess().getTypeTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullSumTypeFactor returns EffectFullSumTypeFactor
	 *
	 * Constraint:
	 *     adtElement=Type
	 */
	protected void sequence_EffectFullSumTypeFactor(ISerializationContext context, EffectFullSumTypeFactor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_SUM_TYPE_FACTOR__ADT_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_SUM_TYPE_FACTOR__ADT_ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullSumTypeFactorAccess().getAdtElementTypeParserRuleCall_1_0(), semanticObject.getAdtElement());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns EffectFullSumValue
	 *     EffectFullExpression returns EffectFullSumValue
	 *     EffectFullSumValue returns EffectFullSumValue
	 *
	 * Constraint:
	 *     (sumAdtElement1=EffectFullExpressionAndEffectFullFunctionReference | sumAdtElement2=EffectFullExpressionAndEffectFullFunctionReference)
	 */
	protected void sequence_EffectFullSumValue(ISerializationContext context, EffectFullSumValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullValueBlock returns EffectFullValueBlock
	 *
	 * Constraint:
	 *     elements+=EffectFullValue+
	 */
	protected void sequence_EffectFullValueBlock(ISerializationContext context, EffectFullValueBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullBodyContent returns EffectFullValueRef
	 *     EffectFullExpression returns EffectFullValueRef
	 *     EffectFullValueRef returns EffectFullValueRef
	 *
	 * Constraint:
	 *     value=[EffectFullValue|ID]
	 */
	protected void sequence_EffectFullValueRef(ISerializationContext context, EffectFullValueRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_VALUE_REF__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_VALUE_REF__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullValueRefAccess().getValueEffectFullValueIDTerminalRuleCall_3_0_1(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EffectFullValue returns EffectFullValue
	 *     Function returns EffectFullValue
	 *     EffectFullFunction returns EffectFullValue
	 *     EffectFullBodyContent returns EffectFullValue
	 *
	 * Constraint:
	 *     (name=ID value=EffectFullExpression)
	 */
	protected void sequence_EffectFullValue(ISerializationContext context, EffectFullValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_DEFINITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_FUNCTION_DEFINITION__NAME));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EFFECT_FULL_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EFFECT_FULL_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEffectFullValueAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getEffectFullValueAccess().getValueEffectFullExpressionParserRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     FunctionBodyPure returns EmptyFunctionBody
	 *     FunctionBodyEffectFull returns EmptyFunctionBody
	 *     EmptyFunctionBody returns EmptyFunctionBody
	 *
	 * Constraint:
	 *     {EmptyFunctionBody}
	 */
	protected void sequence_EmptyFunctionBody(ISerializationContext context, EmptyFunctionBody semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Equals
	 *     PureFunction returns Equals
	 *     PrimitiveFunction returns Equals
	 *     PrimitivePureFunction returns Equals
	 *     Equals returns Equals
	 *
	 * Constraint:
	 *     (type=IntegerType | type=StringType | type=BooleanType)
	 */
	protected void sequence_Equals(ISerializationContext context, Equals semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns ExtractEffectFull
	 *     EffectFullFunction returns ExtractEffectFull
	 *     PrimitiveFunction returns ExtractEffectFull
	 *     EffectFullPrimitive returns ExtractEffectFull
	 *     EffectFullBodyContent returns ExtractEffectFull
	 *     PrimitiveEffectFullFunction returns ExtractEffectFull
	 *     ExtractEffectFull returns ExtractEffectFull
	 *
	 * Constraint:
	 *     data=[EffectFullData|ID]
	 */
	protected void sequence_ExtractEffectFull(ISerializationContext context, ExtractEffectFull semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EXTRACT_EFFECT_FULL__DATA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EXTRACT_EFFECT_FULL__DATA));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExtractEffectFullAccess().getDataEffectFullDataIDTerminalRuleCall_2_0_1(), semanticObject.getData());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns ExtractPure
	 *     PureFunction returns ExtractPure
	 *     PrimitiveFunction returns ExtractPure
	 *     PrimitivePureFunction returns ExtractPure
	 *     ExtractPure returns ExtractPure
	 *
	 * Constraint:
	 *     data=[PureData|ID]
	 */
	protected void sequence_ExtractPure(ISerializationContext context, ExtractPure semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.EXTRACT_PURE__DATA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.EXTRACT_PURE__DATA));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExtractPureAccess().getDataPureDataIDTerminalRuleCall_2_0_1(), semanticObject.getData());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureFunctionType
	 *     PureFunction returns PureFunctionType
	 *     Expression returns PureFunctionType
	 *     FunctionValue returns PureFunctionType
	 *
	 * Constraint:
	 *     value=PureLambda
	 */
	protected void sequence_FunctionValue(ISerializationContext context, PureFunctionType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_TYPE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_TYPE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFunctionValueAccess().getValuePureLambdaParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns GetIntStdIn
	 *     EffectFullFunction returns GetIntStdIn
	 *     PrimitiveFunction returns GetIntStdIn
	 *     EffectFullPrimitive returns GetIntStdIn
	 *     EffectFullBodyContent returns GetIntStdIn
	 *     PrimitiveEffectFullFunction returns GetIntStdIn
	 *     GetIntSdtIn returns GetIntStdIn
	 *
	 * Constraint:
	 *     {GetIntStdIn}
	 */
	protected void sequence_GetIntSdtIn(ISerializationContext context, GetIntStdIn semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns GetLineStdIn
	 *     EffectFullFunction returns GetLineStdIn
	 *     PrimitiveFunction returns GetLineStdIn
	 *     EffectFullPrimitive returns GetLineStdIn
	 *     EffectFullBodyContent returns GetLineStdIn
	 *     PrimitiveEffectFullFunction returns GetLineStdIn
	 *     GetLineStdIn returns GetLineStdIn
	 *
	 * Constraint:
	 *     {GetLineStdIn}
	 */
	protected void sequence_GetLineStdIn(ISerializationContext context, GetLineStdIn semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     IOType returns IOType
	 *     Type returns IOType
	 *     EffectFullType returns IOType
	 *
	 * Constraint:
	 *     type=Type
	 */
	protected void sequence_IOType(ISerializationContext context, IOType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IO_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IO_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIOTypeAccess().getTypeTypeParserRuleCall_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IntPow
	 *     PureFunction returns IntPow
	 *     PrimitiveFunction returns IntPow
	 *     PrimitivePureFunction returns IntPow
	 *     IntPow returns IntPow
	 *
	 * Constraint:
	 *     {IntPow}
	 */
	protected void sequence_IntPow(ISerializationContext context, IntPow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IntToString
	 *     PureFunction returns IntToString
	 *     PrimitiveFunction returns IntToString
	 *     PrimitivePureFunction returns IntToString
	 *     IntToString returns IntToString
	 *
	 * Constraint:
	 *     {IntToString}
	 */
	protected void sequence_IntToString(ISerializationContext context, IntToString semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IntegerType
	 *     PureFunction returns IntegerType
	 *     Expression returns IntegerType
	 *     IntValue returns IntegerType
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_IntValue(ISerializationContext context, IntegerType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.INTEGER_TYPE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.INTEGER_TYPE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntValueAccess().getValueINTTerminalRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns IntegerType
	 *     Type returns IntegerType
	 *     IntegerType returns IntegerType
	 *
	 * Constraint:
	 *     type='int'
	 */
	protected void sequence_IntegerType(ISerializationContext context, IntegerType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.INTEGER_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.INTEGER_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntegerTypeAccess().getTypeIntKeyword_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IsLeftEffectFull
	 *     EffectFullFunction returns IsLeftEffectFull
	 *     PrimitiveFunction returns IsLeftEffectFull
	 *     EffectFullPrimitive returns IsLeftEffectFull
	 *     EffectFullBodyContent returns IsLeftEffectFull
	 *     PrimitiveEffectFullFunction returns IsLeftEffectFull
	 *     IsLeftEffectFull returns IsLeftEffectFull
	 *
	 * Constraint:
	 *     type=EffectFullAlgebraicType
	 */
	protected void sequence_IsLeftEffectFull(ISerializationContext context, IsLeftEffectFull semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IS_LEFT_EFFECT_FULL__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IS_LEFT_EFFECT_FULL__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIsLeftEffectFullAccess().getTypeEffectFullAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IsLeftPure
	 *     PureFunction returns IsLeftPure
	 *     PrimitiveFunction returns IsLeftPure
	 *     PrimitivePureFunction returns IsLeftPure
	 *     IsLeftPure returns IsLeftPure
	 *
	 * Constraint:
	 *     type=PureAlgebraicType
	 */
	protected void sequence_IsLeftPure(ISerializationContext context, IsLeftPure semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IS_LEFT_PURE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IS_LEFT_PURE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIsLeftPureAccess().getTypePureAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IsRightEffectFull
	 *     EffectFullFunction returns IsRightEffectFull
	 *     PrimitiveFunction returns IsRightEffectFull
	 *     EffectFullPrimitive returns IsRightEffectFull
	 *     EffectFullBodyContent returns IsRightEffectFull
	 *     PrimitiveEffectFullFunction returns IsRightEffectFull
	 *     IsRightEffectFull returns IsRightEffectFull
	 *
	 * Constraint:
	 *     type=EffectFullAlgebraicType
	 */
	protected void sequence_IsRightEffectFull(ISerializationContext context, IsRightEffectFull semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IS_RIGHT_EFFECT_FULL__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IS_RIGHT_EFFECT_FULL__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIsRightEffectFullAccess().getTypeEffectFullAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns IsRightPure
	 *     PureFunction returns IsRightPure
	 *     PrimitiveFunction returns IsRightPure
	 *     PrimitivePureFunction returns IsRightPure
	 *     IsRightPure returns IsRightPure
	 *
	 * Constraint:
	 *     type=PureAlgebraicType
	 */
	protected void sequence_IsRightPure(ISerializationContext context, IsRightPure semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.IS_RIGHT_PURE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.IS_RIGHT_PURE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIsRightPureAccess().getTypePureAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LeftAlgebraicIO
	 *     EffectFullFunction returns LeftAlgebraicIO
	 *     PrimitiveFunction returns LeftAlgebraicIO
	 *     EffectFullPrimitive returns LeftAlgebraicIO
	 *     EffectFullBodyContent returns LeftAlgebraicIO
	 *     PrimitiveEffectFullFunction returns LeftAlgebraicIO
	 *     LeftAlgebraicIO returns LeftAlgebraicIO
	 *
	 * Constraint:
	 *     type=EffectFullAlgebraicType
	 */
	protected void sequence_LeftAlgebraicIO(ISerializationContext context, LeftAlgebraicIO semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.LEFT_ALGEBRAIC_IO__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.LEFT_ALGEBRAIC_IO__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLeftAlgebraicIOAccess().getTypeEffectFullAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LeftAlgebraic
	 *     PureFunction returns LeftAlgebraic
	 *     PrimitiveFunction returns LeftAlgebraic
	 *     PrimitivePureFunction returns LeftAlgebraic
	 *     LeftAlgebraic returns LeftAlgebraic
	 *
	 * Constraint:
	 *     type=PureAlgebraicType
	 */
	protected void sequence_LeftAlgebraic(ISerializationContext context, LeftAlgebraic semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.LEFT_ALGEBRAIC__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.LEFT_ALGEBRAIC__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLeftAlgebraicAccess().getTypePureAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LiftEffectFullFunction
	 *     EffectFullFunction returns LiftEffectFullFunction
	 *     PrimitiveFunction returns LiftEffectFullFunction
	 *     EffectFullPrimitive returns LiftEffectFullFunction
	 *     EffectFullBodyContent returns LiftEffectFullFunction
	 *     PrimitiveEffectFullFunction returns LiftEffectFullFunction
	 *     LiftEffectFullFunction returns LiftEffectFullFunction
	 *
	 * Constraint:
	 *     (functionRef=[EffectFullFunction|ID] | functionPrimitive=PrimitiveEffectFullFunction)
	 */
	protected void sequence_LiftEffectFullFunction(ISerializationContext context, LiftEffectFullFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LiftPureFunction
	 *     EffectFullFunction returns LiftPureFunction
	 *     PrimitiveFunction returns LiftPureFunction
	 *     EffectFullPrimitive returns LiftPureFunction
	 *     EffectFullBodyContent returns LiftPureFunction
	 *     PrimitiveEffectFullFunction returns LiftPureFunction
	 *     LiftPureFunction returns LiftPureFunction
	 *
	 * Constraint:
	 *     (functionRef=[PureFunction|ID] | functionPrimitive=PrimitivePureFunction)
	 */
	protected void sequence_LiftPureFunction(ISerializationContext context, LiftPureFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LogicAnd
	 *     PureFunction returns LogicAnd
	 *     PrimitiveFunction returns LogicAnd
	 *     PrimitivePureFunction returns LogicAnd
	 *     LogicAnd returns LogicAnd
	 *
	 * Constraint:
	 *     {LogicAnd}
	 */
	protected void sequence_LogicAnd(ISerializationContext context, LogicAnd semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LogicNot
	 *     PureFunction returns LogicNot
	 *     PrimitiveFunction returns LogicNot
	 *     PrimitivePureFunction returns LogicNot
	 *     LogicNot returns LogicNot
	 *
	 * Constraint:
	 *     {LogicNot}
	 */
	protected void sequence_LogicNot(ISerializationContext context, LogicNot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns LogicOr
	 *     PureFunction returns LogicOr
	 *     PrimitiveFunction returns LogicOr
	 *     PrimitivePureFunction returns LogicOr
	 *     LogicOr returns LogicOr
	 *
	 * Constraint:
	 *     {LogicOr}
	 */
	protected void sequence_LogicOr(ISerializationContext context, LogicOr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MainFunc returns MainFunc
	 *
	 * Constraint:
	 *     (returnType=UnitType functionBody=FunctionBodyEffectFull)
	 */
	protected void sequence_MainFunc(ISerializationContext context, MainFunc semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.MAIN_FUNC__RETURN_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.MAIN_FUNC__RETURN_TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.MAIN_FUNC__FUNCTION_BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.MAIN_FUNC__FUNCTION_BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMainFuncAccess().getReturnTypeUnitTypeParserRuleCall_1_0(), semanticObject.getReturnType());
		feeder.accept(grammarAccess.getMainFuncAccess().getFunctionBodyFunctionBodyEffectFullParserRuleCall_5_0(), semanticObject.getFunctionBody());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns MajorEquals
	 *     PureFunction returns MajorEquals
	 *     PrimitiveFunction returns MajorEquals
	 *     PrimitivePureFunction returns MajorEquals
	 *     MajorEquals returns MajorEquals
	 *
	 * Constraint:
	 *     {MajorEquals}
	 */
	protected void sequence_MajorEquals(ISerializationContext context, MajorEquals semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Major
	 *     PureFunction returns Major
	 *     PrimitiveFunction returns Major
	 *     PrimitivePureFunction returns Major
	 *     Major returns Major
	 *
	 * Constraint:
	 *     {Major}
	 */
	protected void sequence_Major(ISerializationContext context, Major semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns MinorEquals
	 *     PureFunction returns MinorEquals
	 *     PrimitiveFunction returns MinorEquals
	 *     PrimitivePureFunction returns MinorEquals
	 *     MinorEquals returns MinorEquals
	 *
	 * Constraint:
	 *     {MinorEquals}
	 */
	protected void sequence_MinorEquals(ISerializationContext context, MinorEquals semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Minor
	 *     PureFunction returns Minor
	 *     PrimitiveFunction returns Minor
	 *     PrimitivePureFunction returns Minor
	 *     Minor returns Minor
	 *
	 * Constraint:
	 *     {Minor}
	 */
	protected void sequence_Minor(ISerializationContext context, Minor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Minus
	 *     PureFunction returns Minus
	 *     PrimitiveFunction returns Minus
	 *     PrimitivePureFunction returns Minus
	 *     Minus returns Minus
	 *
	 * Constraint:
	 *     {Minus}
	 */
	protected void sequence_Minus(ISerializationContext context, Minus semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Mod
	 *     PureFunction returns Mod
	 *     PrimitiveFunction returns Mod
	 *     PrimitivePureFunction returns Mod
	 *     Mod returns Mod
	 *
	 * Constraint:
	 *     {Mod}
	 */
	protected void sequence_Mod(ISerializationContext context, Mod semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (elements+=PureBlock elements+=EffectFullBlock)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Plus
	 *     PureFunction returns Plus
	 *     PrimitiveFunction returns Plus
	 *     PrimitivePureFunction returns Plus
	 *     Plus returns Plus
	 *
	 * Constraint:
	 *     (type=IntegerType | type=StringType)
	 */
	protected void sequence_Plus(ISerializationContext context, Plus semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Print
	 *     EffectFullFunction returns Print
	 *     PrimitiveFunction returns Print
	 *     EffectFullPrimitive returns Print
	 *     EffectFullBodyContent returns Print
	 *     PrimitiveEffectFullFunction returns Print
	 *     Print returns Print
	 *
	 * Constraint:
	 *     {Print}
	 */
	protected void sequence_Print(ISerializationContext context, Print semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns PureAlgebraicType
	 *     Type returns PureAlgebraicType
	 *     PureAlgebraicType returns PureAlgebraicType
	 *
	 * Constraint:
	 *     (pureAdtElement1=ValueType (pureAdtElement2=PureSumTypeFactor | pureAdtElement2=PureProdTypeFactor))
	 */
	protected void sequence_PureAlgebraicType(ISerializationContext context, PureAlgebraicType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureArgument
	 *     PureFunction returns PureArgument
	 *     Argument returns PureArgument
	 *     PureArgument returns PureArgument
	 *
	 * Constraint:
	 *     (type=ValueType name=ID)
	 */
	protected void sequence_PureArgument(ISerializationContext context, PureArgument semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_ARGUMENT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_ARGUMENT__TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_ARGUMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_ARGUMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureArgumentAccess().getTypeValueTypeParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getPureArgumentAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PureBlock returns PureBlock
	 *
	 * Constraint:
	 *     (elements+=PureDataBlock elements+=PureFunctionBlock)
	 */
	protected void sequence_PureBlock(ISerializationContext context, PureBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PureDataBlock returns PureDataBlock
	 *
	 * Constraint:
	 *     (elements+=PureData* value=PureValueBlock)
	 */
	protected void sequence_PureDataBlock(ISerializationContext context, PureDataBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PureData returns PureData
	 *
	 * Constraint:
	 *     (name=ID content=ValueType)
	 */
	protected void sequence_PureData(ISerializationContext context, PureData semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_DATA__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_DATA__NAME));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_DATA__CONTENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_DATA__CONTENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureDataAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPureDataAccess().getContentValueTypeParserRuleCall_2_0(), semanticObject.getContent());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureEitherIf
	 *     PureFunction returns PureEitherIf
	 *     PrimitiveFunction returns PureEitherIf
	 *     PrimitivePureFunction returns PureEitherIf
	 *     PureEitherIf returns PureEitherIf
	 *
	 * Constraint:
	 *     (then=PureIfBody else=PureIfBody)
	 */
	protected void sequence_PureEitherIf(ISerializationContext context, PureEitherIf semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_EITHER_IF__THEN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_EITHER_IF__THEN));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_EITHER_IF__ELSE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_EITHER_IF__ELSE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureEitherIfAccess().getThenPureIfBodyParserRuleCall_4_0(), semanticObject.getThen());
		feeder.accept(grammarAccess.getPureEitherIfAccess().getElsePureIfBodyParserRuleCall_8_0(), semanticObject.getElse());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PureExpressionAndPureFunctionReference returns PureExpressionAndPureFunctionReference
	 *
	 * Constraint:
	 *     (prodAdtElementExpression=Expression | prodAdtElementFunction=[PureFunction|ID])
	 */
	protected void sequence_PureExpressionAndPureFunctionReference(ISerializationContext context, PureExpressionAndPureFunctionReference semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PureFunctionBlock returns PureFunctionBlock
	 *
	 * Constraint:
	 *     features+=PureFunctionDefinition+
	 */
	protected void sequence_PureFunctionBlock(ISerializationContext context, PureFunctionBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PureFunctionDefinition returns PureFunctionDefinition
	 *     Function returns PureFunctionDefinition
	 *     PureFunction returns PureFunctionDefinition
	 *
	 * Constraint:
	 *     (returnType=ValueType name=ID arg=PureArgument higherOrderArg=AdditionalPureArgument? functionBody=FunctionBodyPure)
	 */
	protected void sequence_PureFunctionDefinition(ISerializationContext context, PureFunctionDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns PureFunctionType
	 *     Type returns PureFunctionType
	 *     PureFunctionType returns PureFunctionType
	 *
	 * Constraint:
	 *     (argType=ValueType returnType=ValueType)
	 */
	protected void sequence_PureFunctionType(ISerializationContext context, PureFunctionType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_TYPE__ARG_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_TYPE__ARG_TYPE));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_TYPE__RETURN_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_TYPE__RETURN_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureFunctionTypeAccess().getArgTypeValueTypeParserRuleCall_3_0(), semanticObject.getArgType());
		feeder.accept(grammarAccess.getPureFunctionTypeAccess().getReturnTypeValueTypeParserRuleCall_5_0(), semanticObject.getReturnType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PureIfBody returns PureIfBody
	 *
	 * Constraint:
	 *     (functionReference=[PureFunction|ID] | functionExpression=Expression)
	 */
	protected void sequence_PureIfBody(ISerializationContext context, PureIfBody semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureIf
	 *     PureFunction returns PureIf
	 *     PrimitiveFunction returns PureIf
	 *     PrimitivePureFunction returns PureIf
	 *     PureIf returns PureIf
	 *
	 * Constraint:
	 *     (then=PureIfBody else=PureIfBody)
	 */
	protected void sequence_PureIf(ISerializationContext context, PureIf semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_IF__THEN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_IF__THEN));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_IF__ELSE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_IF__ELSE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureIfAccess().getThenPureIfBodyParserRuleCall_4_0(), semanticObject.getThen());
		feeder.accept(grammarAccess.getPureIfAccess().getElsePureIfBodyParserRuleCall_8_0(), semanticObject.getElse());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PureLambda returns PureLambda
	 *
	 * Constraint:
	 *     ((arg=PureArgument functionBody=CompositionFunctionBodyPure) | functionBody=CompositionFunctionBodyPure)
	 */
	protected void sequence_PureLambda(ISerializationContext context, PureLambda semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PureProdTypeFactor returns PureProdTypeFactor
	 *
	 * Constraint:
	 *     adtElement=ValueType
	 */
	protected void sequence_PureProdTypeFactor(ISerializationContext context, PureProdTypeFactor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureProdTypeFactorAccess().getAdtElementValueTypeParserRuleCall_1_0(), semanticObject.getAdtElement());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureProdValue
	 *     PureFunction returns PureProdValue
	 *     Expression returns PureProdValue
	 *     PureProdValue returns PureProdValue
	 *
	 * Constraint:
	 *     (prodAdtElement1=PureExpressionAndPureFunctionReference prodAdtElement2=PureExpressionAndPureFunctionReference)
	 */
	protected void sequence_PureProdValue(ISerializationContext context, PureProdValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_PROD_VALUE__PROD_ADT_ELEMENT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_PROD_VALUE__PROD_ADT_ELEMENT1));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_PROD_VALUE__PROD_ADT_ELEMENT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_PROD_VALUE__PROD_ADT_ELEMENT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureProdValueAccess().getProdAdtElement1PureExpressionAndPureFunctionReferenceParserRuleCall_2_0(), semanticObject.getProdAdtElement1());
		feeder.accept(grammarAccess.getPureProdValueAccess().getProdAdtElement2PureExpressionAndPureFunctionReferenceParserRuleCall_4_0(), semanticObject.getProdAdtElement2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureReturn
	 *     PureFunction returns PureReturn
	 *     PrimitiveFunction returns PureReturn
	 *     PrimitivePureFunction returns PureReturn
	 *     PureReturn returns PureReturn
	 *
	 * Constraint:
	 *     type=ValueType
	 */
	protected void sequence_PureReturn(ISerializationContext context, PureReturn semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_RETURN__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_RETURN__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureReturnAccess().getTypeValueTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PureSumTypeFactor returns PureSumTypeFactor
	 *
	 * Constraint:
	 *     adtElement=ValueType
	 */
	protected void sequence_PureSumTypeFactor(ISerializationContext context, PureSumTypeFactor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_SUM_TYPE_FACTOR__ADT_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_SUM_TYPE_FACTOR__ADT_ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureSumTypeFactorAccess().getAdtElementValueTypeParserRuleCall_1_0(), semanticObject.getAdtElement());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureSumValue
	 *     PureFunction returns PureSumValue
	 *     Expression returns PureSumValue
	 *     PureSumValue returns PureSumValue
	 *
	 * Constraint:
	 *     (sumAdtElement1=PureExpressionAndPureFunctionReference | sumAdtElement2=PureExpressionAndPureFunctionReference)
	 */
	protected void sequence_PureSumValue(ISerializationContext context, PureSumValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PureValueBlock returns PureValueBlock
	 *
	 * Constraint:
	 *     elements+=PureValue+
	 */
	protected void sequence_PureValueBlock(ISerializationContext context, PureValueBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns PureValueRef
	 *     PureFunction returns PureValueRef
	 *     Expression returns PureValueRef
	 *     PureValueRef returns PureValueRef
	 *
	 * Constraint:
	 *     value=[PureValue|ID]
	 */
	protected void sequence_PureValueRef(ISerializationContext context, PureValueRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_VALUE_REF__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_VALUE_REF__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureValueRefAccess().getValuePureValueIDTerminalRuleCall_3_0_1(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PureValue returns PureValue
	 *     Function returns PureValue
	 *     PureFunction returns PureValue
	 *
	 * Constraint:
	 *     (name=ID value=Expression)
	 */
	protected void sequence_PureValue(ISerializationContext context, PureValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_DEFINITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_FUNCTION_DEFINITION__NAME));
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.PURE_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.PURE_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPureValueAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPureValueAccess().getValueExpressionParserRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveFunction returns Random
	 *     EffectFullPrimitive returns Random
	 *     EffectFullBodyContent returns Random
	 *     PrimitiveEffectFullValue returns Random
	 *     Random returns Random
	 *
	 * Constraint:
	 *     {Random}
	 */
	protected void sequence_Random(ISerializationContext context, Random semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns RightAlgebraicIO
	 *     EffectFullFunction returns RightAlgebraicIO
	 *     PrimitiveFunction returns RightAlgebraicIO
	 *     EffectFullPrimitive returns RightAlgebraicIO
	 *     EffectFullBodyContent returns RightAlgebraicIO
	 *     PrimitiveEffectFullFunction returns RightAlgebraicIO
	 *     RightAlgebraicIO returns RightAlgebraicIO
	 *
	 * Constraint:
	 *     type=EffectFullAlgebraicType
	 */
	protected void sequence_RightAlgebraicIO(ISerializationContext context, RightAlgebraicIO semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.RIGHT_ALGEBRAIC_IO__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.RIGHT_ALGEBRAIC_IO__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRightAlgebraicIOAccess().getTypeEffectFullAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns RightAlgebraic
	 *     PureFunction returns RightAlgebraic
	 *     PrimitiveFunction returns RightAlgebraic
	 *     PrimitivePureFunction returns RightAlgebraic
	 *     RightAlgebraic returns RightAlgebraic
	 *
	 * Constraint:
	 *     type=PureAlgebraicType
	 */
	protected void sequence_RightAlgebraic(ISerializationContext context, RightAlgebraic semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.RIGHT_ALGEBRAIC__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.RIGHT_ALGEBRAIC__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRightAlgebraicAccess().getTypePureAlgebraicTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns StringType
	 *     Type returns StringType
	 *     StringType returns StringType
	 *
	 * Constraint:
	 *     type='String'
	 */
	protected void sequence_StringType(ISerializationContext context, StringType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.STRING_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.STRING_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringTypeAccess().getTypeStringKeyword_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns StringType
	 *     PureFunction returns StringType
	 *     Expression returns StringType
	 *     StringValue returns StringType
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_StringValue(ISerializationContext context, StringType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.STRING_TYPE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.STRING_TYPE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringValueAccess().getValueSTRINGTerminalRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PrimitiveFunction returns Time
	 *     EffectFullPrimitive returns Time
	 *     EffectFullBodyContent returns Time
	 *     PrimitiveEffectFullValue returns Time
	 *     Time returns Time
	 *
	 * Constraint:
	 *     {Time}
	 */
	protected void sequence_Time(ISerializationContext context, Time semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Times
	 *     PureFunction returns Times
	 *     PrimitiveFunction returns Times
	 *     PrimitivePureFunction returns Times
	 *     Times returns Times
	 *
	 * Constraint:
	 *     {Times}
	 */
	protected void sequence_Times(ISerializationContext context, Times semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ValueType returns UnitType
	 *     Type returns UnitType
	 *     UnitType returns UnitType
	 *
	 * Constraint:
	 *     type='Unit'
	 */
	protected void sequence_UnitType(ISerializationContext context, UnitType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FPMLPackage.Literals.UNIT_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FPMLPackage.Literals.UNIT_TYPE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUnitTypeAccess().getTypeUnitKeyword_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns UnitType
	 *     PureFunction returns UnitType
	 *     UnitValue returns UnitType
	 *     Expression returns UnitType
	 *
	 * Constraint:
	 *     {UnitType}
	 */
	protected void sequence_UnitValue(ISerializationContext context, UnitType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns VoidType
	 *     EffectFullType returns VoidType
	 *     VoidType returns VoidType
	 *
	 * Constraint:
	 *     {VoidType}
	 */
	protected void sequence_VoidType(ISerializationContext context, VoidType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
