/*
 * generated by Xtext 2.10.0
 */
package it.unibo.ui;

import com.google.inject.Injector;
import fpml.ui.internal.FpmlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FPMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FpmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FpmlActivator.getInstance().getInjector(FpmlActivator.IT_UNIBO_FPML);
	}
	
}
