/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.ApplyFIOFactor;
import it.unibo.fPML.EffectFullExpression;
import it.unibo.fPML.EffectFullFunction;
import it.unibo.fPML.EffectFullPrimitive;
import it.unibo.fPML.FPMLPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Apply FIO Factor</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.ApplyFIOFactorImpl#getValueReference <em>Value Reference</em>}</li>
 *   <li>{@link it.unibo.fPML.impl.ApplyFIOFactorImpl#getValuePrimitive <em>Value Primitive</em>}</li>
 *   <li>{@link it.unibo.fPML.impl.ApplyFIOFactorImpl#getValueExpression <em>Value Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ApplyFIOFactorImpl extends MinimalEObjectImpl.Container implements ApplyFIOFactor
{
  /**
   * The cached value of the '{@link #getValueReference() <em>Value Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueReference()
   * @generated
   * @ordered
   */
  protected EffectFullFunction valueReference;

  /**
   * The cached value of the '{@link #getValuePrimitive() <em>Value Primitive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValuePrimitive()
   * @generated
   * @ordered
   */
  protected EffectFullPrimitive valuePrimitive;

  /**
   * The cached value of the '{@link #getValueExpression() <em>Value Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueExpression()
   * @generated
   * @ordered
   */
  protected EffectFullExpression valueExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ApplyFIOFactorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.APPLY_FIO_FACTOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullFunction getValueReference()
  {
    if (valueReference != null && valueReference.eIsProxy())
    {
      InternalEObject oldValueReference = (InternalEObject)valueReference;
      valueReference = (EffectFullFunction)eResolveProxy(oldValueReference);
      if (valueReference != oldValueReference)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FPMLPackage.APPLY_FIO_FACTOR__VALUE_REFERENCE, oldValueReference, valueReference));
      }
    }
    return valueReference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullFunction basicGetValueReference()
  {
    return valueReference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueReference(EffectFullFunction newValueReference)
  {
    EffectFullFunction oldValueReference = valueReference;
    valueReference = newValueReference;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.APPLY_FIO_FACTOR__VALUE_REFERENCE, oldValueReference, valueReference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullPrimitive getValuePrimitive()
  {
    return valuePrimitive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValuePrimitive(EffectFullPrimitive newValuePrimitive, NotificationChain msgs)
  {
    EffectFullPrimitive oldValuePrimitive = valuePrimitive;
    valuePrimitive = newValuePrimitive;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE, oldValuePrimitive, newValuePrimitive);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValuePrimitive(EffectFullPrimitive newValuePrimitive)
  {
    if (newValuePrimitive != valuePrimitive)
    {
      NotificationChain msgs = null;
      if (valuePrimitive != null)
        msgs = ((InternalEObject)valuePrimitive).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE, null, msgs);
      if (newValuePrimitive != null)
        msgs = ((InternalEObject)newValuePrimitive).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE, null, msgs);
      msgs = basicSetValuePrimitive(newValuePrimitive, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE, newValuePrimitive, newValuePrimitive));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullExpression getValueExpression()
  {
    return valueExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValueExpression(EffectFullExpression newValueExpression, NotificationChain msgs)
  {
    EffectFullExpression oldValueExpression = valueExpression;
    valueExpression = newValueExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION, oldValueExpression, newValueExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueExpression(EffectFullExpression newValueExpression)
  {
    if (newValueExpression != valueExpression)
    {
      NotificationChain msgs = null;
      if (valueExpression != null)
        msgs = ((InternalEObject)valueExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION, null, msgs);
      if (newValueExpression != null)
        msgs = ((InternalEObject)newValueExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION, null, msgs);
      msgs = basicSetValueExpression(newValueExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION, newValueExpression, newValueExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE:
        return basicSetValuePrimitive(null, msgs);
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION:
        return basicSetValueExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_REFERENCE:
        if (resolve) return getValueReference();
        return basicGetValueReference();
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE:
        return getValuePrimitive();
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION:
        return getValueExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_REFERENCE:
        setValueReference((EffectFullFunction)newValue);
        return;
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE:
        setValuePrimitive((EffectFullPrimitive)newValue);
        return;
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION:
        setValueExpression((EffectFullExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_REFERENCE:
        setValueReference((EffectFullFunction)null);
        return;
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE:
        setValuePrimitive((EffectFullPrimitive)null);
        return;
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION:
        setValueExpression((EffectFullExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_REFERENCE:
        return valueReference != null;
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_PRIMITIVE:
        return valuePrimitive != null;
      case FPMLPackage.APPLY_FIO_FACTOR__VALUE_EXPRESSION:
        return valueExpression != null;
    }
    return super.eIsSet(featureID);
  }

} //ApplyFIOFactorImpl
