/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.BoolToString;
import it.unibo.fPML.FPMLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bool To String</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BoolToStringImpl extends PrimitivePureFunctionImpl implements BoolToString
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoolToStringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.BOOL_TO_STRING;
  }

} //BoolToStringImpl
