/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.EffectFullAdtType;
import it.unibo.fPML.FPMLPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Effect Full Adt Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.EffectFullAdtTypeImpl#getEffectFullAdtElement1 <em>Effect Full Adt Element1</em>}</li>
 *   <li>{@link it.unibo.fPML.impl.EffectFullAdtTypeImpl#getEffectFullAdtElement2 <em>Effect Full Adt Element2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EffectFullAdtTypeImpl extends MinimalEObjectImpl.Container implements EffectFullAdtType
{
  /**
   * The cached value of the '{@link #getEffectFullAdtElement1() <em>Effect Full Adt Element1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEffectFullAdtElement1()
   * @generated
   * @ordered
   */
  protected EffectFullAdtType effectFullAdtElement1;

  /**
   * The cached value of the '{@link #getEffectFullAdtElement2() <em>Effect Full Adt Element2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEffectFullAdtElement2()
   * @generated
   * @ordered
   */
  protected EObject effectFullAdtElement2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EffectFullAdtTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.EFFECT_FULL_ADT_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullAdtType getEffectFullAdtElement1()
  {
    return effectFullAdtElement1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEffectFullAdtElement1(EffectFullAdtType newEffectFullAdtElement1, NotificationChain msgs)
  {
    EffectFullAdtType oldEffectFullAdtElement1 = effectFullAdtElement1;
    effectFullAdtElement1 = newEffectFullAdtElement1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1, oldEffectFullAdtElement1, newEffectFullAdtElement1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEffectFullAdtElement1(EffectFullAdtType newEffectFullAdtElement1)
  {
    if (newEffectFullAdtElement1 != effectFullAdtElement1)
    {
      NotificationChain msgs = null;
      if (effectFullAdtElement1 != null)
        msgs = ((InternalEObject)effectFullAdtElement1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1, null, msgs);
      if (newEffectFullAdtElement1 != null)
        msgs = ((InternalEObject)newEffectFullAdtElement1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1, null, msgs);
      msgs = basicSetEffectFullAdtElement1(newEffectFullAdtElement1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1, newEffectFullAdtElement1, newEffectFullAdtElement1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getEffectFullAdtElement2()
  {
    return effectFullAdtElement2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEffectFullAdtElement2(EObject newEffectFullAdtElement2, NotificationChain msgs)
  {
    EObject oldEffectFullAdtElement2 = effectFullAdtElement2;
    effectFullAdtElement2 = newEffectFullAdtElement2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2, oldEffectFullAdtElement2, newEffectFullAdtElement2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEffectFullAdtElement2(EObject newEffectFullAdtElement2)
  {
    if (newEffectFullAdtElement2 != effectFullAdtElement2)
    {
      NotificationChain msgs = null;
      if (effectFullAdtElement2 != null)
        msgs = ((InternalEObject)effectFullAdtElement2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2, null, msgs);
      if (newEffectFullAdtElement2 != null)
        msgs = ((InternalEObject)newEffectFullAdtElement2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2, null, msgs);
      msgs = basicSetEffectFullAdtElement2(newEffectFullAdtElement2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2, newEffectFullAdtElement2, newEffectFullAdtElement2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1:
        return basicSetEffectFullAdtElement1(null, msgs);
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2:
        return basicSetEffectFullAdtElement2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1:
        return getEffectFullAdtElement1();
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2:
        return getEffectFullAdtElement2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1:
        setEffectFullAdtElement1((EffectFullAdtType)newValue);
        return;
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2:
        setEffectFullAdtElement2((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1:
        setEffectFullAdtElement1((EffectFullAdtType)null);
        return;
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2:
        setEffectFullAdtElement2((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT1:
        return effectFullAdtElement1 != null;
      case FPMLPackage.EFFECT_FULL_ADT_TYPE__EFFECT_FULL_ADT_ELEMENT2:
        return effectFullAdtElement2 != null;
    }
    return super.eIsSet(featureID);
  }

} //EffectFullAdtTypeImpl
