/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.EffectFullExpression;
import it.unibo.fPML.EffectFullSumValue;
import it.unibo.fPML.FPMLPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Effect Full Sum Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.EffectFullSumValueImpl#getSumAdtElement1 <em>Sum Adt Element1</em>}</li>
 *   <li>{@link it.unibo.fPML.impl.EffectFullSumValueImpl#getSumAdtElement2 <em>Sum Adt Element2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EffectFullSumValueImpl extends EffectFullAlgebraicTypeImpl implements EffectFullSumValue
{
  /**
   * The cached value of the '{@link #getSumAdtElement1() <em>Sum Adt Element1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSumAdtElement1()
   * @generated
   * @ordered
   */
  protected EffectFullExpression sumAdtElement1;

  /**
   * The cached value of the '{@link #getSumAdtElement2() <em>Sum Adt Element2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSumAdtElement2()
   * @generated
   * @ordered
   */
  protected EffectFullExpression sumAdtElement2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EffectFullSumValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.EFFECT_FULL_SUM_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullExpression getSumAdtElement1()
  {
    return sumAdtElement1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSumAdtElement1(EffectFullExpression newSumAdtElement1, NotificationChain msgs)
  {
    EffectFullExpression oldSumAdtElement1 = sumAdtElement1;
    sumAdtElement1 = newSumAdtElement1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1, oldSumAdtElement1, newSumAdtElement1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSumAdtElement1(EffectFullExpression newSumAdtElement1)
  {
    if (newSumAdtElement1 != sumAdtElement1)
    {
      NotificationChain msgs = null;
      if (sumAdtElement1 != null)
        msgs = ((InternalEObject)sumAdtElement1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1, null, msgs);
      if (newSumAdtElement1 != null)
        msgs = ((InternalEObject)newSumAdtElement1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1, null, msgs);
      msgs = basicSetSumAdtElement1(newSumAdtElement1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1, newSumAdtElement1, newSumAdtElement1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EffectFullExpression getSumAdtElement2()
  {
    return sumAdtElement2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSumAdtElement2(EffectFullExpression newSumAdtElement2, NotificationChain msgs)
  {
    EffectFullExpression oldSumAdtElement2 = sumAdtElement2;
    sumAdtElement2 = newSumAdtElement2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2, oldSumAdtElement2, newSumAdtElement2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSumAdtElement2(EffectFullExpression newSumAdtElement2)
  {
    if (newSumAdtElement2 != sumAdtElement2)
    {
      NotificationChain msgs = null;
      if (sumAdtElement2 != null)
        msgs = ((InternalEObject)sumAdtElement2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2, null, msgs);
      if (newSumAdtElement2 != null)
        msgs = ((InternalEObject)newSumAdtElement2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2, null, msgs);
      msgs = basicSetSumAdtElement2(newSumAdtElement2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2, newSumAdtElement2, newSumAdtElement2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1:
        return basicSetSumAdtElement1(null, msgs);
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2:
        return basicSetSumAdtElement2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1:
        return getSumAdtElement1();
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2:
        return getSumAdtElement2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1:
        setSumAdtElement1((EffectFullExpression)newValue);
        return;
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2:
        setSumAdtElement2((EffectFullExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1:
        setSumAdtElement1((EffectFullExpression)null);
        return;
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2:
        setSumAdtElement2((EffectFullExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT1:
        return sumAdtElement1 != null;
      case FPMLPackage.EFFECT_FULL_SUM_VALUE__SUM_ADT_ELEMENT2:
        return sumAdtElement2 != null;
    }
    return super.eIsSet(featureID);
  }

} //EffectFullSumValueImpl
