/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.EmptyFunctionBody;
import it.unibo.fPML.FPMLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Empty Function Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EmptyFunctionBodyImpl extends FunctionBodyPureImpl implements EmptyFunctionBody
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EmptyFunctionBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.EMPTY_FUNCTION_BODY;
  }

} //EmptyFunctionBodyImpl
