/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.GetIntSdtIn;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Get Int Sdt In</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GetIntSdtInImpl extends PrimitiveEffectFullFunctionImpl implements GetIntSdtIn
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GetIntSdtInImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.GET_INT_SDT_IN;
  }

} //GetIntSdtInImpl
