/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.ProdType;
import it.unibo.fPML.ValueType;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prod Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.ProdTypeImpl#getProdAdtElements <em>Prod Adt Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProdTypeImpl extends AdtImpl implements ProdType
{
  /**
   * The cached value of the '{@link #getProdAdtElements() <em>Prod Adt Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProdAdtElements()
   * @generated
   * @ordered
   */
  protected EList<ValueType> prodAdtElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProdTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.PROD_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ValueType> getProdAdtElements()
  {
    if (prodAdtElements == null)
    {
      prodAdtElements = new EObjectContainmentEList<ValueType>(ValueType.class, this, FPMLPackage.PROD_TYPE__PROD_ADT_ELEMENTS);
    }
    return prodAdtElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.PROD_TYPE__PROD_ADT_ELEMENTS:
        return ((InternalEList<?>)getProdAdtElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.PROD_TYPE__PROD_ADT_ELEMENTS:
        return getProdAdtElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.PROD_TYPE__PROD_ADT_ELEMENTS:
        getProdAdtElements().clear();
        getProdAdtElements().addAll((Collection<? extends ValueType>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.PROD_TYPE__PROD_ADT_ELEMENTS:
        getProdAdtElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.PROD_TYPE__PROD_ADT_ELEMENTS:
        return prodAdtElements != null && !prodAdtElements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ProdTypeImpl
