/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.PureProdTypeFactor;
import it.unibo.fPML.ValueType;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pure Prod Type Factor</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.PureProdTypeFactorImpl#getAdtElement <em>Adt Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PureProdTypeFactorImpl extends MinimalEObjectImpl.Container implements PureProdTypeFactor
{
  /**
   * The cached value of the '{@link #getAdtElement() <em>Adt Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdtElement()
   * @generated
   * @ordered
   */
  protected ValueType adtElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PureProdTypeFactorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.PURE_PROD_TYPE_FACTOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValueType getAdtElement()
  {
    return adtElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdtElement(ValueType newAdtElement, NotificationChain msgs)
  {
    ValueType oldAdtElement = adtElement;
    adtElement = newAdtElement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT, oldAdtElement, newAdtElement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdtElement(ValueType newAdtElement)
  {
    if (newAdtElement != adtElement)
    {
      NotificationChain msgs = null;
      if (adtElement != null)
        msgs = ((InternalEObject)adtElement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT, null, msgs);
      if (newAdtElement != null)
        msgs = ((InternalEObject)newAdtElement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT, null, msgs);
      msgs = basicSetAdtElement(newAdtElement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT, newAdtElement, newAdtElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT:
        return basicSetAdtElement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT:
        return getAdtElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT:
        setAdtElement((ValueType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT:
        setAdtElement((ValueType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.PURE_PROD_TYPE_FACTOR__ADT_ELEMENT:
        return adtElement != null;
    }
    return super.eIsSet(featureID);
  }

} //PureProdTypeFactorImpl
