/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.RecursiveEffectFullExpression;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Recursive Effect Full Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RecursiveEffectFullExpressionImpl extends EffectFullExpressionImpl implements RecursiveEffectFullExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RecursiveEffectFullExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.RECURSIVE_EFFECT_FULL_EXPRESSION;
  }

} //RecursiveEffectFullExpressionImpl
