/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.FunctionBodyPure;
import it.unibo.fPML.ReturnPureFunction;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Return Pure Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.ReturnPureFunctionImpl#getLambdaFunctioBody <em>Lambda Functio Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReturnPureFunctionImpl extends MinimalEObjectImpl.Container implements ReturnPureFunction
{
  /**
   * The cached value of the '{@link #getLambdaFunctioBody() <em>Lambda Functio Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLambdaFunctioBody()
   * @generated
   * @ordered
   */
  protected FunctionBodyPure lambdaFunctioBody;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReturnPureFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.RETURN_PURE_FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionBodyPure getLambdaFunctioBody()
  {
    return lambdaFunctioBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLambdaFunctioBody(FunctionBodyPure newLambdaFunctioBody, NotificationChain msgs)
  {
    FunctionBodyPure oldLambdaFunctioBody = lambdaFunctioBody;
    lambdaFunctioBody = newLambdaFunctioBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY, oldLambdaFunctioBody, newLambdaFunctioBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLambdaFunctioBody(FunctionBodyPure newLambdaFunctioBody)
  {
    if (newLambdaFunctioBody != lambdaFunctioBody)
    {
      NotificationChain msgs = null;
      if (lambdaFunctioBody != null)
        msgs = ((InternalEObject)lambdaFunctioBody).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY, null, msgs);
      if (newLambdaFunctioBody != null)
        msgs = ((InternalEObject)newLambdaFunctioBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY, null, msgs);
      msgs = basicSetLambdaFunctioBody(newLambdaFunctioBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY, newLambdaFunctioBody, newLambdaFunctioBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY:
        return basicSetLambdaFunctioBody(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY:
        return getLambdaFunctioBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY:
        setLambdaFunctioBody((FunctionBodyPure)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY:
        setLambdaFunctioBody((FunctionBodyPure)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.RETURN_PURE_FUNCTION__LAMBDA_FUNCTIO_BODY:
        return lambdaFunctioBody != null;
    }
    return super.eIsSet(featureID);
  }

} //ReturnPureFunctionImpl
