/**
 * generated by Xtext 2.10.0
 */
package it.unibo.fPML.impl;

import it.unibo.fPML.FPMLPackage;
import it.unibo.fPML.SumType;
import it.unibo.fPML.ValueType;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sum Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.fPML.impl.SumTypeImpl#getSumAdtElements <em>Sum Adt Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SumTypeImpl extends AdtImpl implements SumType
{
  /**
   * The cached value of the '{@link #getSumAdtElements() <em>Sum Adt Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSumAdtElements()
   * @generated
   * @ordered
   */
  protected EList<ValueType> sumAdtElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SumTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FPMLPackage.Literals.SUM_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ValueType> getSumAdtElements()
  {
    if (sumAdtElements == null)
    {
      sumAdtElements = new EObjectContainmentEList<ValueType>(ValueType.class, this, FPMLPackage.SUM_TYPE__SUM_ADT_ELEMENTS);
    }
    return sumAdtElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FPMLPackage.SUM_TYPE__SUM_ADT_ELEMENTS:
        return ((InternalEList<?>)getSumAdtElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FPMLPackage.SUM_TYPE__SUM_ADT_ELEMENTS:
        return getSumAdtElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FPMLPackage.SUM_TYPE__SUM_ADT_ELEMENTS:
        getSumAdtElements().clear();
        getSumAdtElements().addAll((Collection<? extends ValueType>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.SUM_TYPE__SUM_ADT_ELEMENTS:
        getSumAdtElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FPMLPackage.SUM_TYPE__SUM_ADT_ELEMENTS:
        return sumAdtElements != null && !sumAdtElements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SumTypeImpl
